//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boxes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boxes()
        {
            this.BoxMoves = new HashSet<BoxMoves>();
            this.Transfers = new HashSet<Transfers>();
        }
    
        public int ID { get; set; }
        public int ConnID { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateS { get; set; }
        public Nullable<System.DateTime> DateE { get; set; }
        public decimal AmountInit { get; set; }
        public decimal Incomes { get; set; }
        public decimal Expenses { get; set; }
        public decimal Sales { get; set; }
        public bool IsOpen { get; set; }
        public string ClosedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxMoves> BoxMoves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfers> Transfers { get; set; }
    }
}
