//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxMoves
    {
        public int ID { get; set; }
        public int BoxID { get; set; }
        public string UserID { get; set; }
        public decimal Amount { get; set; }
        public byte Type { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
    
        public virtual Boxes Boxes { get; set; }
    }
}
