//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connections
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Server { get; set; }
        public string DB { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string RIF { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Image { get; set; }
        public bool UseFactOnline { get; set; }
        public string UserToken { get; set; }
        public string PassToken { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> DateToken { get; set; }
    }
}
