//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HttpTraces
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string RequestMethod { get; set; }
        public string RequestUrl { get; set; }
        public string RequestHeaders { get; set; }
        public string RequestContent { get; set; }
        public Nullable<int> ResponseStatusCode { get; set; }
        public string ResponseReasonPhrase { get; set; }
        public string ResponseHeaders { get; set; }
        public string ResponseContent { get; set; }
        public Nullable<long> DurationMs { get; set; }
        public Nullable<bool> IsSuccessStatusCode { get; set; }
        public string ExceptionMessage { get; set; }
    }
}
