//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsFactOnline
    {
        public string NroFact { get; set; }
        public int Status { get; set; }
        public System.DateTime DateInserted { get; set; }
        public Nullable<System.DateTime> DateTried { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Message { get; set; }
        public int ConnID { get; set; }
        public string BodyJson { get; set; }
        public string NroControl { get; set; }
    }
}
