//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsFactOnline
    {
        public string NroFact { get; set; }
        public string Serie { get; set; }
        public int ConnID { get; set; }
        public string BodyJson { get; set; }
        public int Status { get; set; }
        public string HttpCode { get; set; }
        public int Times { get; set; }
        public string NroControl { get; set; }
        public System.DateTime DateInserted { get; set; }
        public Nullable<System.DateTime> DateTried { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Message { get; set; }
    }
}
