//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Options()
        {
            this.UserOptions = new HashSet<UserOptions>();
        }
    
        public int ID { get; set; }
        public string OptionName { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string OptionType { get; set; }
        public int Number { get; set; }
        public string URL { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Modules Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOptions> UserOptions { get; set; }
    }
}
