//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProfitAdmEntities : DbContext
    {
        public ProfitAdmEntities(string conn) : base(conn)
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<par_emp> par_emp { get; set; }
        public virtual DbSet<pvArticuloExt> pvArticuloExt { get; set; }
        public virtual DbSet<pvCaja> pvCaja { get; set; }
        public virtual DbSet<pvCobroExt> pvCobroExt { get; set; }
        public virtual DbSet<pvCobroTPRengExt> pvCobroTPRengExt { get; set; }
        public virtual DbSet<pvConfigPuntoV> pvConfigPuntoV { get; set; }
        public virtual DbSet<pvConfigPuntoVPrecio> pvConfigPuntoVPrecio { get; set; }
        public virtual DbSet<pvDevolucionClienteExt> pvDevolucionClienteExt { get; set; }
        public virtual DbSet<pvEtiquetaBalanza> pvEtiquetaBalanza { get; set; }
        public virtual DbSet<pvFacturaVentaExt> pvFacturaVentaExt { get; set; }
        public virtual DbSet<pvMovimientoBancoExt> pvMovimientoBancoExt { get; set; }
        public virtual DbSet<pvMovimientoCajaDevolucionExt> pvMovimientoCajaDevolucionExt { get; set; }
        public virtual DbSet<pvMovimientoCajaExt> pvMovimientoCajaExt { get; set; }
        public virtual DbSet<pvParEmp> pvParEmp { get; set; }
        public virtual DbSet<pvRenglonTicket> pvRenglonTicket { get; set; }
        public virtual DbSet<pvTarjetaCreditoExt> pvTarjetaCreditoExt { get; set; }
        public virtual DbSet<pvTipoTarjeta> pvTipoTarjeta { get; set; }
        public virtual DbSet<pvTurno> pvTurno { get; set; }
        public virtual DbSet<pvTurnoExe> pvTurnoExe { get; set; }
        public virtual DbSet<pvValeAlimentacion> pvValeAlimentacion { get; set; }
        public virtual DbSet<pvValeAlimentacionReng> pvValeAlimentacionReng { get; set; }
        public virtual DbSet<saAdiCampo> saAdiCampo { get; set; }
        public virtual DbSet<saAdiGrupo> saAdiGrupo { get; set; }
        public virtual DbSet<saAjPrecioCostoAuto> saAjPrecioCostoAuto { get; set; }
        public virtual DbSet<saAjPrecioCostoM> saAjPrecioCostoM { get; set; }
        public virtual DbSet<saAjPrecioCostoReng> saAjPrecioCostoReng { get; set; }
        public virtual DbSet<saAjuste> saAjuste { get; set; }
        public virtual DbSet<saAjusteReng> saAjusteReng { get; set; }
        public virtual DbSet<saAlmacen> saAlmacen { get; set; }
        public virtual DbSet<saAreaImpresion> saAreaImpresion { get; set; }
        public virtual DbSet<saArtCaracteristica> saArtCaracteristica { get; set; }
        public virtual DbSet<saArtCaracteristicaMov> saArtCaracteristicaMov { get; set; }
        public virtual DbSet<saArtCompuesto> saArtCompuesto { get; set; }
        public virtual DbSet<saArtCompuestoGen> saArtCompuestoGen { get; set; }
        public virtual DbSet<saArtCompuestoGenReng> saArtCompuestoGenReng { get; set; }
        public virtual DbSet<saArtCompuestoReng> saArtCompuestoReng { get; set; }
        public virtual DbSet<saArticulo> saArticulo { get; set; }
        public virtual DbSet<saArtIdentificadorReng> saArtIdentificadorReng { get; set; }
        public virtual DbSet<saArtImagen> saArtImagen { get; set; }
        public virtual DbSet<saArtImportacion> saArtImportacion { get; set; }
        public virtual DbSet<saArtMargen> saArtMargen { get; set; }
        public virtual DbSet<saArtPrecio> saArtPrecio { get; set; }
        public virtual DbSet<saArtProveedorReng> saArtProveedorReng { get; set; }
        public virtual DbSet<saArtRelacionadoReng> saArtRelacionadoReng { get; set; }
        public virtual DbSet<saArtUbicacion> saArtUbicacion { get; set; }
        public virtual DbSet<saArtUnidad> saArtUnidad { get; set; }
        public virtual DbSet<saBanco> saBanco { get; set; }
        public virtual DbSet<saBeneficiario> saBeneficiario { get; set; }
        public virtual DbSet<saCaja> saCaja { get; set; }
        public virtual DbSet<saCatArticulo> saCatArticulo { get; set; }
        public virtual DbSet<saCheque> saCheque { get; set; }
        public virtual DbSet<saChequeDevueltoCompra> saChequeDevueltoCompra { get; set; }
        public virtual DbSet<saChequeDevueltoVenta> saChequeDevueltoVenta { get; set; }
        public virtual DbSet<saChequera> saChequera { get; set; }
        public virtual DbSet<saCliente> saCliente { get; set; }
        public virtual DbSet<saClienteExt> saClienteExt { get; set; }
        public virtual DbSet<saCobro> saCobro { get; set; }
        public virtual DbSet<saCobroDocReng> saCobroDocReng { get; set; }
        public virtual DbSet<saCobroRentenReng> saCobroRentenReng { get; set; }
        public virtual DbSet<saCobroRetenIvaReng> saCobroRetenIvaReng { get; set; }
        public virtual DbSet<saCobroTPReng> saCobroTPReng { get; set; }
        public virtual DbSet<saColor> saColor { get; set; }
        public virtual DbSet<saComisionGeneracion> saComisionGeneracion { get; set; }
        public virtual DbSet<saComisionPrecioArticulo> saComisionPrecioArticulo { get; set; }
        public virtual DbSet<saComisionPrecioCategoria> saComisionPrecioCategoria { get; set; }
        public virtual DbSet<saComisionPrecioLinea> saComisionPrecioLinea { get; set; }
        public virtual DbSet<saComisionRentabArticulo> saComisionRentabArticulo { get; set; }
        public virtual DbSet<saComisionRentabCategoria> saComisionRentabCategoria { get; set; }
        public virtual DbSet<saComisionRentabLinea> saComisionRentabLinea { get; set; }
        public virtual DbSet<saComisionResultado> saComisionResultado { get; set; }
        public virtual DbSet<saComisionTipo> saComisionTipo { get; set; }
        public virtual DbSet<saConcBanco> saConcBanco { get; set; }
        public virtual DbSet<saConciliacionAutoReng> saConciliacionAutoReng { get; set; }
        public virtual DbSet<saConciliacionDetalle> saConciliacionDetalle { get; set; }
        public virtual DbSet<saCondicionPago> saCondicionPago { get; set; }
        public virtual DbSet<saConfigAjuste> saConfigAjuste { get; set; }
        public virtual DbSet<saConfigArticulo> saConfigArticulo { get; set; }
        public virtual DbSet<saConfigCliente> saConfigCliente { get; set; }
        public virtual DbSet<saConfigCobro> saConfigCobro { get; set; }
        public virtual DbSet<saConfigCotizacionCliente> saConfigCotizacionCliente { get; set; }
        public virtual DbSet<saConfigCotizacionProveedor> saConfigCotizacionProveedor { get; set; }
        public virtual DbSet<saConfigDevolucionCliente> saConfigDevolucionCliente { get; set; }
        public virtual DbSet<saConfigDevolucionProveedor> saConfigDevolucionProveedor { get; set; }
        public virtual DbSet<saConfigDistCosto> saConfigDistCosto { get; set; }
        public virtual DbSet<saConfigFacturaCompra> saConfigFacturaCompra { get; set; }
        public virtual DbSet<saConfigFacturaVenta> saConfigFacturaVenta { get; set; }
        public virtual DbSet<saConfigMovBanco> saConfigMovBanco { get; set; }
        public virtual DbSet<saConfigMovCaja> saConfigMovCaja { get; set; }
        public virtual DbSet<saConfigNotaDespachoVenta> saConfigNotaDespachoVenta { get; set; }
        public virtual DbSet<saConfigNotaEntregaVenta> saConfigNotaEntregaVenta { get; set; }
        public virtual DbSet<saConfigNotaRecepcionCompra> saConfigNotaRecepcionCompra { get; set; }
        public virtual DbSet<saConfigOrdenCompra> saConfigOrdenCompra { get; set; }
        public virtual DbSet<saConfigOrdenPago> saConfigOrdenPago { get; set; }
        public virtual DbSet<saConfigPago> saConfigPago { get; set; }
        public virtual DbSet<saConfigPedidoVenta> saConfigPedidoVenta { get; set; }
        public virtual DbSet<saConfigPlantillaCompra> saConfigPlantillaCompra { get; set; }
        public virtual DbSet<saConfigPlantillaVenta> saConfigPlantillaVenta { get; set; }
        public virtual DbSet<saConfigProveedor> saConfigProveedor { get; set; }
        public virtual DbSet<saConfigTraslado> saConfigTraslado { get; set; }
        public virtual DbSet<saConISLR> saConISLR { get; set; }
        public virtual DbSet<saConsecutivo> saConsecutivo { get; set; }
        public virtual DbSet<saConsecutivoTipo> saConsecutivoTipo { get; set; }
        public virtual DbSet<saCostoHistoricoEntrada> saCostoHistoricoEntrada { get; set; }
        public virtual DbSet<saCostoHistoricoSalida> saCostoHistoricoSalida { get; set; }
        public virtual DbSet<saCotizacionCliente> saCotizacionCliente { get; set; }
        public virtual DbSet<saCotizacionClienteReng> saCotizacionClienteReng { get; set; }
        public virtual DbSet<saCotizacionProveedor> saCotizacionProveedor { get; set; }
        public virtual DbSet<saCotizacionProveedorReng> saCotizacionProveedorReng { get; set; }
        public virtual DbSet<saCuentaBancaria> saCuentaBancaria { get; set; }
        public virtual DbSet<saCuentaIngEgr> saCuentaIngEgr { get; set; }
        public virtual DbSet<saDatosDeImportacion> saDatosDeImportacion { get; set; }
        public virtual DbSet<saDepositoBanco> saDepositoBanco { get; set; }
        public virtual DbSet<saDepositoBancoReng> saDepositoBancoReng { get; set; }
        public virtual DbSet<saDescArticulo> saDescArticulo { get; set; }
        public virtual DbSet<saDescCategoria> saDescCategoria { get; set; }
        public virtual DbSet<saDescLinea> saDescLinea { get; set; }
        public virtual DbSet<saDescProntoPago> saDescProntoPago { get; set; }
        public virtual DbSet<saDevolucionCliente> saDevolucionCliente { get; set; }
        public virtual DbSet<saDevolucionClienteReng> saDevolucionClienteReng { get; set; }
        public virtual DbSet<saDevolucionProveedor> saDevolucionProveedor { get; set; }
        public virtual DbSet<saDevolucionProveedorReng> saDevolucionProveedorReng { get; set; }
        public virtual DbSet<saDevolucionProveedorRengExt> saDevolucionProveedorRengExt { get; set; }
        public virtual DbSet<saDistribCosto> saDistribCosto { get; set; }
        public virtual DbSet<saDistribCostoDestinoReng> saDistribCostoDestinoReng { get; set; }
        public virtual DbSet<saDistribCostoOrigenReng> saDistribCostoOrigenReng { get; set; }
        public virtual DbSet<saDistribCostoRelaReng> saDistribCostoRelaReng { get; set; }
        public virtual DbSet<saDocumentoCompra> saDocumentoCompra { get; set; }
        public virtual DbSet<saDocumentoCompraReng> saDocumentoCompraReng { get; set; }
        public virtual DbSet<saDocumentoElectronico> saDocumentoElectronico { get; set; }
        public virtual DbSet<saDocumentoImagen> saDocumentoImagen { get; set; }
        public virtual DbSet<saDocumentoVenta> saDocumentoVenta { get; set; }
        public virtual DbSet<saDocumentoVentaReng> saDocumentoVentaReng { get; set; }
        public virtual DbSet<saFactCompRengCaracteristicasAdic> saFactCompRengCaracteristicasAdic { get; set; }
        public virtual DbSet<saFactCompRengPesoVolumen> saFactCompRengPesoVolumen { get; set; }
        public virtual DbSet<saFacturaCompra> saFacturaCompra { get; set; }
        public virtual DbSet<saFacturaCompraImportacion> saFacturaCompraImportacion { get; set; }
        public virtual DbSet<saFacturaCompraReng> saFacturaCompraReng { get; set; }
        public virtual DbSet<saFacturaCompraRengExt> saFacturaCompraRengExt { get; set; }
        public virtual DbSet<saFacturaVenta> saFacturaVenta { get; set; }
        public virtual DbSet<saFacturaVentaReng> saFacturaVentaReng { get; set; }
        public virtual DbSet<saGiroCompra> saGiroCompra { get; set; }
        public virtual DbSet<saGiroCompraReng> saGiroCompraReng { get; set; }
        public virtual DbSet<saGiroVenta> saGiroVenta { get; set; }
        public virtual DbSet<saGiroVentaReng> saGiroVentaReng { get; set; }
        public virtual DbSet<saHistoricoEstado> saHistoricoEstado { get; set; }
        public virtual DbSet<saImpMun> saImpMun { get; set; }
        public virtual DbSet<saImpuesto> saImpuesto { get; set; }
        public virtual DbSet<saImpuestoReng> saImpuestoReng { get; set; }
        public virtual DbSet<saImpuestoSobreVenta> saImpuestoSobreVenta { get; set; }
        public virtual DbSet<saImpuestoSobreVentaReng> saImpuestoSobreVentaReng { get; set; }
        public virtual DbSet<saIncoterm> saIncoterm { get; set; }
        public virtual DbSet<saIntegr> saIntegr { get; set; }
        public virtual DbSet<saInventarioFisico> saInventarioFisico { get; set; }
        public virtual DbSet<saLineaArticulo> saLineaArticulo { get; set; }
        public virtual DbSet<saLoteEntrada> saLoteEntrada { get; set; }
        public virtual DbSet<saLoteSalida> saLoteSalida { get; set; }
        public virtual DbSet<saMoneda> saMoneda { get; set; }
        public virtual DbSet<saMovimientoBanco> saMovimientoBanco { get; set; }
        public virtual DbSet<saMovimientoCaja> saMovimientoCaja { get; set; }
        public virtual DbSet<saNCFInfoDocCompra> saNCFInfoDocCompra { get; set; }
        public virtual DbSet<saNCFInfoDocVenta> saNCFInfoDocVenta { get; set; }
        public virtual DbSet<saNotaDespachoVenta> saNotaDespachoVenta { get; set; }
        public virtual DbSet<saNotaDespachoVentaReng> saNotaDespachoVentaReng { get; set; }
        public virtual DbSet<saNotaEntregaVenta> saNotaEntregaVenta { get; set; }
        public virtual DbSet<saNotaEntregaVentaReng> saNotaEntregaVentaReng { get; set; }
        public virtual DbSet<saNotaRecepcionCompra> saNotaRecepcionCompra { get; set; }
        public virtual DbSet<saNotaRecepcionCompraReng> saNotaRecepcionCompraReng { get; set; }
        public virtual DbSet<saOrdenCompra> saOrdenCompra { get; set; }
        public virtual DbSet<saOrdenCompraReng> saOrdenCompraReng { get; set; }
        public virtual DbSet<saOrdenPago> saOrdenPago { get; set; }
        public virtual DbSet<saOrdenPagoReng> saOrdenPagoReng { get; set; }
        public virtual DbSet<saPago> saPago { get; set; }
        public virtual DbSet<saPagoDocReng> saPagoDocReng { get; set; }
        public virtual DbSet<saPagoRentenReng> saPagoRentenReng { get; set; }
        public virtual DbSet<saPagoRetenIvaReng> saPagoRetenIvaReng { get; set; }
        public virtual DbSet<saPagoTPReng> saPagoTPReng { get; set; }
        public virtual DbSet<saPais> saPais { get; set; }
        public virtual DbSet<saParametroConc> saParametroConc { get; set; }
        public virtual DbSet<saPedidoVenta> saPedidoVenta { get; set; }
        public virtual DbSet<saPedidoVentaReng> saPedidoVentaReng { get; set; }
        public virtual DbSet<saPista> saPista { get; set; }
        public virtual DbSet<saPlanillaFiscal> saPlanillaFiscal { get; set; }
        public virtual DbSet<saPlantillaCompra> saPlantillaCompra { get; set; }
        public virtual DbSet<saPlantillaCompraReng> saPlantillaCompraReng { get; set; }
        public virtual DbSet<saPlantillaCompraReq> saPlantillaCompraReq { get; set; }
        public virtual DbSet<saPlantillaCompraReqRelacion> saPlantillaCompraReqRelacion { get; set; }
        public virtual DbSet<saPlantillaCompraReqRenglon> saPlantillaCompraReqRenglon { get; set; }
        public virtual DbSet<saPlantillaVenta> saPlantillaVenta { get; set; }
        public virtual DbSet<saPlantillaVentaReng> saPlantillaVentaReng { get; set; }
        public virtual DbSet<saProcedencia> saProcedencia { get; set; }
        public virtual DbSet<saProveedor> saProveedor { get; set; }
        public virtual DbSet<saProveedorExt> saProveedorExt { get; set; }
        public virtual DbSet<saPuntoEmision> saPuntoEmision { get; set; }
        public virtual DbSet<saReglaInt> saReglaInt { get; set; }
        public virtual DbSet<saResInventario> saResInventario { get; set; }
        public virtual DbSet<saResInventarioReng> saResInventarioReng { get; set; }
        public virtual DbSet<saSaldoBanco> saSaldoBanco { get; set; }
        public virtual DbSet<saSaldoCaja> saSaldoCaja { get; set; }
        public virtual DbSet<saSegmento> saSegmento { get; set; }
        public virtual DbSet<saSeriales> saSeriales { get; set; }
        public virtual DbSet<saSerie> saSerie { get; set; }
        public virtual DbSet<saSerieTipo> saSerieTipo { get; set; }
        public virtual DbSet<saSerieTipoExt> saSerieTipoExt { get; set; }
        public virtual DbSet<saStockAlmacen> saStockAlmacen { get; set; }
        public virtual DbSet<saSubLinea> saSubLinea { get; set; }
        public virtual DbSet<saSucursal> saSucursal { get; set; }
        public virtual DbSet<saTabuladorIslr> saTabuladorIslr { get; set; }
        public virtual DbSet<saTabuladorIslrReng> saTabuladorIslrReng { get; set; }
        public virtual DbSet<saTarjetaCredito> saTarjetaCredito { get; set; }
        public virtual DbSet<saTasa> saTasa { get; set; }
        public virtual DbSet<saTax> saTax { get; set; }
        public virtual DbSet<saTipoAjuste> saTipoAjuste { get; set; }
        public virtual DbSet<saTipoAnulacionVenta> saTipoAnulacionVenta { get; set; }
        public virtual DbSet<saTipoCliente> saTipoCliente { get; set; }
        public virtual DbSet<saTipoComprobante> saTipoComprobante { get; set; }
        public virtual DbSet<saTipoDocumento> saTipoDocumento { get; set; }
        public virtual DbSet<saTipoGasto> saTipoGasto { get; set; }
        public virtual DbSet<saTipoImagen> saTipoImagen { get; set; }
        public virtual DbSet<saTipoPrecio> saTipoPrecio { get; set; }
        public virtual DbSet<saTipoProveedor> saTipoProveedor { get; set; }
        public virtual DbSet<saTransferenciaEntreCuentas> saTransferenciaEntreCuentas { get; set; }
        public virtual DbSet<saTransporte> saTransporte { get; set; }
        public virtual DbSet<saTraslado> saTraslado { get; set; }
        public virtual DbSet<saTrasladoReng> saTrasladoReng { get; set; }
        public virtual DbSet<saUbicacion> saUbicacion { get; set; }
        public virtual DbSet<saUnidad> saUnidad { get; set; }
        public virtual DbSet<saUnidadTributaria> saUnidadTributaria { get; set; }
        public virtual DbSet<saVendedor> saVendedor { get; set; }
        public virtual DbSet<saZona> saZona { get; set; }
        public virtual DbSet<scCentro> scCentro { get; set; }
        public virtual DbSet<scCuenta> scCuenta { get; set; }
        public virtual DbSet<scGastos> scGastos { get; set; }
        public virtual DbSet<stgFactLoteGen> stgFactLoteGen { get; set; }
        public virtual DbSet<stgFacturaVentaExt> stgFacturaVentaExt { get; set; }
        public virtual DbSet<pvDenominacionesMoneda> pvDenominacionesMoneda { get; set; }
        public virtual DbSet<saArtCrearAut> saArtCrearAut { get; set; }
    
        public virtual ObjectResult<RepEstadoCuentaCli_Result> RepEstadoCuentaCli(Nullable<System.DateTime> dFecha_d, Nullable<System.DateTime> dFecha_h, string sCo_Cli, string sCo_Zon_d, string sCo_Zon_h, string sCo_Moneda, string sCo_Seg_d, string sCo_Seg_h, string sTipo_pro, string sDetalle, string sProve_sin_mov, string sCo_Sucursal, string sCampOrderBy, string sDir, Nullable<bool> bHeaderRep)
        {
            var dFecha_dParameter = dFecha_d.HasValue ?
                new ObjectParameter("dFecha_d", dFecha_d) :
                new ObjectParameter("dFecha_d", typeof(System.DateTime));
    
            var dFecha_hParameter = dFecha_h.HasValue ?
                new ObjectParameter("dFecha_h", dFecha_h) :
                new ObjectParameter("dFecha_h", typeof(System.DateTime));
    
            var sCo_CliParameter = sCo_Cli != null ?
                new ObjectParameter("sCo_Cli", sCo_Cli) :
                new ObjectParameter("sCo_Cli", typeof(string));
    
            var sCo_Zon_dParameter = sCo_Zon_d != null ?
                new ObjectParameter("sCo_Zon_d", sCo_Zon_d) :
                new ObjectParameter("sCo_Zon_d", typeof(string));
    
            var sCo_Zon_hParameter = sCo_Zon_h != null ?
                new ObjectParameter("sCo_Zon_h", sCo_Zon_h) :
                new ObjectParameter("sCo_Zon_h", typeof(string));
    
            var sCo_MonedaParameter = sCo_Moneda != null ?
                new ObjectParameter("sCo_Moneda", sCo_Moneda) :
                new ObjectParameter("sCo_Moneda", typeof(string));
    
            var sCo_Seg_dParameter = sCo_Seg_d != null ?
                new ObjectParameter("sCo_Seg_d", sCo_Seg_d) :
                new ObjectParameter("sCo_Seg_d", typeof(string));
    
            var sCo_Seg_hParameter = sCo_Seg_h != null ?
                new ObjectParameter("sCo_Seg_h", sCo_Seg_h) :
                new ObjectParameter("sCo_Seg_h", typeof(string));
    
            var sTipo_proParameter = sTipo_pro != null ?
                new ObjectParameter("sTipo_pro", sTipo_pro) :
                new ObjectParameter("sTipo_pro", typeof(string));
    
            var sDetalleParameter = sDetalle != null ?
                new ObjectParameter("sDetalle", sDetalle) :
                new ObjectParameter("sDetalle", typeof(string));
    
            var sProve_sin_movParameter = sProve_sin_mov != null ?
                new ObjectParameter("sProve_sin_mov", sProve_sin_mov) :
                new ObjectParameter("sProve_sin_mov", typeof(string));
    
            var sCo_SucursalParameter = sCo_Sucursal != null ?
                new ObjectParameter("sCo_Sucursal", sCo_Sucursal) :
                new ObjectParameter("sCo_Sucursal", typeof(string));
    
            var sCampOrderByParameter = sCampOrderBy != null ?
                new ObjectParameter("sCampOrderBy", sCampOrderBy) :
                new ObjectParameter("sCampOrderBy", typeof(string));
    
            var sDirParameter = sDir != null ?
                new ObjectParameter("sDir", sDir) :
                new ObjectParameter("sDir", typeof(string));
    
            var bHeaderRepParameter = bHeaderRep.HasValue ?
                new ObjectParameter("bHeaderRep", bHeaderRep) :
                new ObjectParameter("bHeaderRep", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepEstadoCuentaCli_Result>("RepEstadoCuentaCli", dFecha_dParameter, dFecha_hParameter, sCo_CliParameter, sCo_Zon_dParameter, sCo_Zon_hParameter, sCo_MonedaParameter, sCo_Seg_dParameter, sCo_Seg_hParameter, sTipo_proParameter, sDetalleParameter, sProve_sin_movParameter, sCo_SucursalParameter, sCampOrderByParameter, sDirParameter, bHeaderRepParameter);
        }
    
        public virtual ObjectResult<RepClienteMasVenta_Result> RepClienteMasVenta(Nullable<System.DateTime> dFecha_Emis_d, Nullable<System.DateTime> dFecha_Emis_h, string sCo_Cli_d, string sCo_Cli_h, string sCo_Moneda, string sCo_Zon_d, string sCo_Zon_h, string sCo_Seg_d, string sCo_Seg_h, Nullable<int> iCantidad, string sCo_Sucursal, string sCampOrderBy, string sDir, Nullable<bool> bHeaderRep)
        {
            var dFecha_Emis_dParameter = dFecha_Emis_d.HasValue ?
                new ObjectParameter("dFecha_Emis_d", dFecha_Emis_d) :
                new ObjectParameter("dFecha_Emis_d", typeof(System.DateTime));
    
            var dFecha_Emis_hParameter = dFecha_Emis_h.HasValue ?
                new ObjectParameter("dFecha_Emis_h", dFecha_Emis_h) :
                new ObjectParameter("dFecha_Emis_h", typeof(System.DateTime));
    
            var sCo_Cli_dParameter = sCo_Cli_d != null ?
                new ObjectParameter("sCo_Cli_d", sCo_Cli_d) :
                new ObjectParameter("sCo_Cli_d", typeof(string));
    
            var sCo_Cli_hParameter = sCo_Cli_h != null ?
                new ObjectParameter("sCo_Cli_h", sCo_Cli_h) :
                new ObjectParameter("sCo_Cli_h", typeof(string));
    
            var sCo_MonedaParameter = sCo_Moneda != null ?
                new ObjectParameter("sCo_Moneda", sCo_Moneda) :
                new ObjectParameter("sCo_Moneda", typeof(string));
    
            var sCo_Zon_dParameter = sCo_Zon_d != null ?
                new ObjectParameter("sCo_Zon_d", sCo_Zon_d) :
                new ObjectParameter("sCo_Zon_d", typeof(string));
    
            var sCo_Zon_hParameter = sCo_Zon_h != null ?
                new ObjectParameter("sCo_Zon_h", sCo_Zon_h) :
                new ObjectParameter("sCo_Zon_h", typeof(string));
    
            var sCo_Seg_dParameter = sCo_Seg_d != null ?
                new ObjectParameter("sCo_Seg_d", sCo_Seg_d) :
                new ObjectParameter("sCo_Seg_d", typeof(string));
    
            var sCo_Seg_hParameter = sCo_Seg_h != null ?
                new ObjectParameter("sCo_Seg_h", sCo_Seg_h) :
                new ObjectParameter("sCo_Seg_h", typeof(string));
    
            var iCantidadParameter = iCantidad.HasValue ?
                new ObjectParameter("iCantidad", iCantidad) :
                new ObjectParameter("iCantidad", typeof(int));
    
            var sCo_SucursalParameter = sCo_Sucursal != null ?
                new ObjectParameter("sCo_Sucursal", sCo_Sucursal) :
                new ObjectParameter("sCo_Sucursal", typeof(string));
    
            var sCampOrderByParameter = sCampOrderBy != null ?
                new ObjectParameter("sCampOrderBy", sCampOrderBy) :
                new ObjectParameter("sCampOrderBy", typeof(string));
    
            var sDirParameter = sDir != null ?
                new ObjectParameter("sDir", sDir) :
                new ObjectParameter("sDir", typeof(string));
    
            var bHeaderRepParameter = bHeaderRep.HasValue ?
                new ObjectParameter("bHeaderRep", bHeaderRep) :
                new ObjectParameter("bHeaderRep", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepClienteMasVenta_Result>("RepClienteMasVenta", dFecha_Emis_dParameter, dFecha_Emis_hParameter, sCo_Cli_dParameter, sCo_Cli_hParameter, sCo_MonedaParameter, sCo_Zon_dParameter, sCo_Zon_hParameter, sCo_Seg_dParameter, sCo_Seg_hParameter, iCantidadParameter, sCo_SucursalParameter, sCampOrderByParameter, sDirParameter, bHeaderRepParameter);
        }
    
        public virtual ObjectResult<RepEstadoCuentaProv_Result> RepEstadoCuentaProv(Nullable<System.DateTime> dFecha_d, Nullable<System.DateTime> dFecha_h, string sCo_Prov, string sCo_Zon_d, string sCo_Zon_h, string sCo_Moneda, string sCo_Seg_d, string sCo_Seg_h, string sTipo_pro, string sDetalle, string sProve_sin_mov, string sCo_Sucursal, string sCampOrderBy, string sDir, Nullable<bool> bHeaderRep)
        {
            var dFecha_dParameter = dFecha_d.HasValue ?
                new ObjectParameter("dFecha_d", dFecha_d) :
                new ObjectParameter("dFecha_d", typeof(System.DateTime));
    
            var dFecha_hParameter = dFecha_h.HasValue ?
                new ObjectParameter("dFecha_h", dFecha_h) :
                new ObjectParameter("dFecha_h", typeof(System.DateTime));
    
            var sCo_ProvParameter = sCo_Prov != null ?
                new ObjectParameter("sCo_Prov", sCo_Prov) :
                new ObjectParameter("sCo_Prov", typeof(string));
    
            var sCo_Zon_dParameter = sCo_Zon_d != null ?
                new ObjectParameter("sCo_Zon_d", sCo_Zon_d) :
                new ObjectParameter("sCo_Zon_d", typeof(string));
    
            var sCo_Zon_hParameter = sCo_Zon_h != null ?
                new ObjectParameter("sCo_Zon_h", sCo_Zon_h) :
                new ObjectParameter("sCo_Zon_h", typeof(string));
    
            var sCo_MonedaParameter = sCo_Moneda != null ?
                new ObjectParameter("sCo_Moneda", sCo_Moneda) :
                new ObjectParameter("sCo_Moneda", typeof(string));
    
            var sCo_Seg_dParameter = sCo_Seg_d != null ?
                new ObjectParameter("sCo_Seg_d", sCo_Seg_d) :
                new ObjectParameter("sCo_Seg_d", typeof(string));
    
            var sCo_Seg_hParameter = sCo_Seg_h != null ?
                new ObjectParameter("sCo_Seg_h", sCo_Seg_h) :
                new ObjectParameter("sCo_Seg_h", typeof(string));
    
            var sTipo_proParameter = sTipo_pro != null ?
                new ObjectParameter("sTipo_pro", sTipo_pro) :
                new ObjectParameter("sTipo_pro", typeof(string));
    
            var sDetalleParameter = sDetalle != null ?
                new ObjectParameter("sDetalle", sDetalle) :
                new ObjectParameter("sDetalle", typeof(string));
    
            var sProve_sin_movParameter = sProve_sin_mov != null ?
                new ObjectParameter("sProve_sin_mov", sProve_sin_mov) :
                new ObjectParameter("sProve_sin_mov", typeof(string));
    
            var sCo_SucursalParameter = sCo_Sucursal != null ?
                new ObjectParameter("sCo_Sucursal", sCo_Sucursal) :
                new ObjectParameter("sCo_Sucursal", typeof(string));
    
            var sCampOrderByParameter = sCampOrderBy != null ?
                new ObjectParameter("sCampOrderBy", sCampOrderBy) :
                new ObjectParameter("sCampOrderBy", typeof(string));
    
            var sDirParameter = sDir != null ?
                new ObjectParameter("sDir", sDir) :
                new ObjectParameter("sDir", typeof(string));
    
            var bHeaderRepParameter = bHeaderRep.HasValue ?
                new ObjectParameter("bHeaderRep", bHeaderRep) :
                new ObjectParameter("bHeaderRep", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepEstadoCuentaProv_Result>("RepEstadoCuentaProv", dFecha_dParameter, dFecha_hParameter, sCo_ProvParameter, sCo_Zon_dParameter, sCo_Zon_hParameter, sCo_MonedaParameter, sCo_Seg_dParameter, sCo_Seg_hParameter, sTipo_proParameter, sDetalleParameter, sProve_sin_movParameter, sCo_SucursalParameter, sCampOrderByParameter, sDirParameter, bHeaderRepParameter);
        }
    
        public virtual ObjectResult<RepProveedorMasCompra_Result> RepProveedorMasCompra(Nullable<System.DateTime> sFecha_Emis_d, Nullable<System.DateTime> sFecha_Emis_h, string sCo_Prov_d, string sCo_Prov_h, Nullable<int> iCantidad, string sCo_Moneda, string sCo_Sucursal, string sCampOrderBy, string sDir, Nullable<bool> bHeaderRep)
        {
            var sFecha_Emis_dParameter = sFecha_Emis_d.HasValue ?
                new ObjectParameter("sFecha_Emis_d", sFecha_Emis_d) :
                new ObjectParameter("sFecha_Emis_d", typeof(System.DateTime));
    
            var sFecha_Emis_hParameter = sFecha_Emis_h.HasValue ?
                new ObjectParameter("sFecha_Emis_h", sFecha_Emis_h) :
                new ObjectParameter("sFecha_Emis_h", typeof(System.DateTime));
    
            var sCo_Prov_dParameter = sCo_Prov_d != null ?
                new ObjectParameter("sCo_Prov_d", sCo_Prov_d) :
                new ObjectParameter("sCo_Prov_d", typeof(string));
    
            var sCo_Prov_hParameter = sCo_Prov_h != null ?
                new ObjectParameter("sCo_Prov_h", sCo_Prov_h) :
                new ObjectParameter("sCo_Prov_h", typeof(string));
    
            var iCantidadParameter = iCantidad.HasValue ?
                new ObjectParameter("iCantidad", iCantidad) :
                new ObjectParameter("iCantidad", typeof(int));
    
            var sCo_MonedaParameter = sCo_Moneda != null ?
                new ObjectParameter("sCo_Moneda", sCo_Moneda) :
                new ObjectParameter("sCo_Moneda", typeof(string));
    
            var sCo_SucursalParameter = sCo_Sucursal != null ?
                new ObjectParameter("sCo_Sucursal", sCo_Sucursal) :
                new ObjectParameter("sCo_Sucursal", typeof(string));
    
            var sCampOrderByParameter = sCampOrderBy != null ?
                new ObjectParameter("sCampOrderBy", sCampOrderBy) :
                new ObjectParameter("sCampOrderBy", typeof(string));
    
            var sDirParameter = sDir != null ?
                new ObjectParameter("sDir", sDir) :
                new ObjectParameter("sDir", typeof(string));
    
            var bHeaderRepParameter = bHeaderRep.HasValue ?
                new ObjectParameter("bHeaderRep", bHeaderRep) :
                new ObjectParameter("bHeaderRep", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepProveedorMasCompra_Result>("RepProveedorMasCompra", sFecha_Emis_dParameter, sFecha_Emis_hParameter, sCo_Prov_dParameter, sCo_Prov_hParameter, iCantidadParameter, sCo_MonedaParameter, sCo_SucursalParameter, sCampOrderByParameter, sDirParameter, bHeaderRepParameter);
        }
    
        public virtual ObjectResult<pInsertarCliente_Result> pInsertarCliente(string sCo_Cli, string sLogin, string sPassword, string sSalesTax, string sCli_Des, string sCo_seg, string sCo_zon, string sCo_Ven, string sEstado, Nullable<bool> bInactivo, Nullable<bool> bValido, Nullable<bool> bSinCredito, Nullable<bool> bLunes, Nullable<bool> bMartes, Nullable<bool> bMiercoles, Nullable<bool> bJueves, Nullable<bool> bViernes, Nullable<bool> bSabado, Nullable<bool> bDomingo, string sDirec1, string sDirec2, string sDir_Ent2, string sHorar_Caja, string sFrecu_Vist, string sTelefonos, string sFax, string sRespons, Nullable<System.DateTime> sdFecha_reg, string sTip_Cli, string sSerialP, Nullable<int> iPuntaje, Nullable<int> iId, Nullable<decimal> deMont_cre, string sCo_mone, string sCond_Pag, Nullable<int> iPlaz_pag, Nullable<decimal> deDesc_ppago, Nullable<decimal> deDesc_Glob, string sTipo_Iva, Nullable<decimal> deIva, string sRif, Nullable<bool> bContrib, string sDis_cen, string sNit, string sEmail, string sCo_Cta_Ingr_Egr, string sComentario, string sCampo1, string sCampo2, string sCampo3, string sCampo4, string sCampo5, string sCampo6, string sCampo7, string sCampo8, string sCo_Us_In, string sMaquina, string sRevisado, string sTrasnfe, string sCo_Sucu_In, Nullable<bool> bJuridico, Nullable<int> iTipo_Adi, string sMatriz, string sCo_Tab, string sTipo_Per, string sCo_pais, string sCiudad, string sZip, string sWebSite, Nullable<bool> bContribu_E, Nullable<bool> bRete_Regis_Doc, Nullable<decimal> dePorc_Esp, string sN_cr, string sN_db, string sTComp, string sEmail_alterno)
        {
            var sCo_CliParameter = sCo_Cli != null ?
                new ObjectParameter("sCo_Cli", sCo_Cli) :
                new ObjectParameter("sCo_Cli", typeof(string));
    
            var sLoginParameter = sLogin != null ?
                new ObjectParameter("sLogin", sLogin) :
                new ObjectParameter("sLogin", typeof(string));
    
            var sPasswordParameter = sPassword != null ?
                new ObjectParameter("sPassword", sPassword) :
                new ObjectParameter("sPassword", typeof(string));
    
            var sSalesTaxParameter = sSalesTax != null ?
                new ObjectParameter("sSalesTax", sSalesTax) :
                new ObjectParameter("sSalesTax", typeof(string));
    
            var sCli_DesParameter = sCli_Des != null ?
                new ObjectParameter("sCli_Des", sCli_Des) :
                new ObjectParameter("sCli_Des", typeof(string));
    
            var sCo_segParameter = sCo_seg != null ?
                new ObjectParameter("sCo_seg", sCo_seg) :
                new ObjectParameter("sCo_seg", typeof(string));
    
            var sCo_zonParameter = sCo_zon != null ?
                new ObjectParameter("sCo_zon", sCo_zon) :
                new ObjectParameter("sCo_zon", typeof(string));
    
            var sCo_VenParameter = sCo_Ven != null ?
                new ObjectParameter("sCo_Ven", sCo_Ven) :
                new ObjectParameter("sCo_Ven", typeof(string));
    
            var sEstadoParameter = sEstado != null ?
                new ObjectParameter("sEstado", sEstado) :
                new ObjectParameter("sEstado", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var bValidoParameter = bValido.HasValue ?
                new ObjectParameter("bValido", bValido) :
                new ObjectParameter("bValido", typeof(bool));
    
            var bSinCreditoParameter = bSinCredito.HasValue ?
                new ObjectParameter("bSinCredito", bSinCredito) :
                new ObjectParameter("bSinCredito", typeof(bool));
    
            var bLunesParameter = bLunes.HasValue ?
                new ObjectParameter("bLunes", bLunes) :
                new ObjectParameter("bLunes", typeof(bool));
    
            var bMartesParameter = bMartes.HasValue ?
                new ObjectParameter("bMartes", bMartes) :
                new ObjectParameter("bMartes", typeof(bool));
    
            var bMiercolesParameter = bMiercoles.HasValue ?
                new ObjectParameter("bMiercoles", bMiercoles) :
                new ObjectParameter("bMiercoles", typeof(bool));
    
            var bJuevesParameter = bJueves.HasValue ?
                new ObjectParameter("bJueves", bJueves) :
                new ObjectParameter("bJueves", typeof(bool));
    
            var bViernesParameter = bViernes.HasValue ?
                new ObjectParameter("bViernes", bViernes) :
                new ObjectParameter("bViernes", typeof(bool));
    
            var bSabadoParameter = bSabado.HasValue ?
                new ObjectParameter("bSabado", bSabado) :
                new ObjectParameter("bSabado", typeof(bool));
    
            var bDomingoParameter = bDomingo.HasValue ?
                new ObjectParameter("bDomingo", bDomingo) :
                new ObjectParameter("bDomingo", typeof(bool));
    
            var sDirec1Parameter = sDirec1 != null ?
                new ObjectParameter("sDirec1", sDirec1) :
                new ObjectParameter("sDirec1", typeof(string));
    
            var sDirec2Parameter = sDirec2 != null ?
                new ObjectParameter("sDirec2", sDirec2) :
                new ObjectParameter("sDirec2", typeof(string));
    
            var sDir_Ent2Parameter = sDir_Ent2 != null ?
                new ObjectParameter("sDir_Ent2", sDir_Ent2) :
                new ObjectParameter("sDir_Ent2", typeof(string));
    
            var sHorar_CajaParameter = sHorar_Caja != null ?
                new ObjectParameter("sHorar_Caja", sHorar_Caja) :
                new ObjectParameter("sHorar_Caja", typeof(string));
    
            var sFrecu_VistParameter = sFrecu_Vist != null ?
                new ObjectParameter("sFrecu_Vist", sFrecu_Vist) :
                new ObjectParameter("sFrecu_Vist", typeof(string));
    
            var sTelefonosParameter = sTelefonos != null ?
                new ObjectParameter("sTelefonos", sTelefonos) :
                new ObjectParameter("sTelefonos", typeof(string));
    
            var sFaxParameter = sFax != null ?
                new ObjectParameter("sFax", sFax) :
                new ObjectParameter("sFax", typeof(string));
    
            var sResponsParameter = sRespons != null ?
                new ObjectParameter("sRespons", sRespons) :
                new ObjectParameter("sRespons", typeof(string));
    
            var sdFecha_regParameter = sdFecha_reg.HasValue ?
                new ObjectParameter("sdFecha_reg", sdFecha_reg) :
                new ObjectParameter("sdFecha_reg", typeof(System.DateTime));
    
            var sTip_CliParameter = sTip_Cli != null ?
                new ObjectParameter("sTip_Cli", sTip_Cli) :
                new ObjectParameter("sTip_Cli", typeof(string));
    
            var sSerialPParameter = sSerialP != null ?
                new ObjectParameter("sSerialP", sSerialP) :
                new ObjectParameter("sSerialP", typeof(string));
    
            var iPuntajeParameter = iPuntaje.HasValue ?
                new ObjectParameter("iPuntaje", iPuntaje) :
                new ObjectParameter("iPuntaje", typeof(int));
    
            var iIdParameter = iId.HasValue ?
                new ObjectParameter("iId", iId) :
                new ObjectParameter("iId", typeof(int));
    
            var deMont_creParameter = deMont_cre.HasValue ?
                new ObjectParameter("deMont_cre", deMont_cre) :
                new ObjectParameter("deMont_cre", typeof(decimal));
    
            var sCo_moneParameter = sCo_mone != null ?
                new ObjectParameter("sCo_mone", sCo_mone) :
                new ObjectParameter("sCo_mone", typeof(string));
    
            var sCond_PagParameter = sCond_Pag != null ?
                new ObjectParameter("sCond_Pag", sCond_Pag) :
                new ObjectParameter("sCond_Pag", typeof(string));
    
            var iPlaz_pagParameter = iPlaz_pag.HasValue ?
                new ObjectParameter("iPlaz_pag", iPlaz_pag) :
                new ObjectParameter("iPlaz_pag", typeof(int));
    
            var deDesc_ppagoParameter = deDesc_ppago.HasValue ?
                new ObjectParameter("deDesc_ppago", deDesc_ppago) :
                new ObjectParameter("deDesc_ppago", typeof(decimal));
    
            var deDesc_GlobParameter = deDesc_Glob.HasValue ?
                new ObjectParameter("deDesc_Glob", deDesc_Glob) :
                new ObjectParameter("deDesc_Glob", typeof(decimal));
    
            var sTipo_IvaParameter = sTipo_Iva != null ?
                new ObjectParameter("sTipo_Iva", sTipo_Iva) :
                new ObjectParameter("sTipo_Iva", typeof(string));
    
            var deIvaParameter = deIva.HasValue ?
                new ObjectParameter("deIva", deIva) :
                new ObjectParameter("deIva", typeof(decimal));
    
            var sRifParameter = sRif != null ?
                new ObjectParameter("sRif", sRif) :
                new ObjectParameter("sRif", typeof(string));
    
            var bContribParameter = bContrib.HasValue ?
                new ObjectParameter("bContrib", bContrib) :
                new ObjectParameter("bContrib", typeof(bool));
    
            var sDis_cenParameter = sDis_cen != null ?
                new ObjectParameter("sDis_cen", sDis_cen) :
                new ObjectParameter("sDis_cen", typeof(string));
    
            var sNitParameter = sNit != null ?
                new ObjectParameter("sNit", sNit) :
                new ObjectParameter("sNit", typeof(string));
    
            var sEmailParameter = sEmail != null ?
                new ObjectParameter("sEmail", sEmail) :
                new ObjectParameter("sEmail", typeof(string));
    
            var sCo_Cta_Ingr_EgrParameter = sCo_Cta_Ingr_Egr != null ?
                new ObjectParameter("sCo_Cta_Ingr_Egr", sCo_Cta_Ingr_Egr) :
                new ObjectParameter("sCo_Cta_Ingr_Egr", typeof(string));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var sCampo1Parameter = sCampo1 != null ?
                new ObjectParameter("sCampo1", sCampo1) :
                new ObjectParameter("sCampo1", typeof(string));
    
            var sCampo2Parameter = sCampo2 != null ?
                new ObjectParameter("sCampo2", sCampo2) :
                new ObjectParameter("sCampo2", typeof(string));
    
            var sCampo3Parameter = sCampo3 != null ?
                new ObjectParameter("sCampo3", sCampo3) :
                new ObjectParameter("sCampo3", typeof(string));
    
            var sCampo4Parameter = sCampo4 != null ?
                new ObjectParameter("sCampo4", sCampo4) :
                new ObjectParameter("sCampo4", typeof(string));
    
            var sCampo5Parameter = sCampo5 != null ?
                new ObjectParameter("sCampo5", sCampo5) :
                new ObjectParameter("sCampo5", typeof(string));
    
            var sCampo6Parameter = sCampo6 != null ?
                new ObjectParameter("sCampo6", sCampo6) :
                new ObjectParameter("sCampo6", typeof(string));
    
            var sCampo7Parameter = sCampo7 != null ?
                new ObjectParameter("sCampo7", sCampo7) :
                new ObjectParameter("sCampo7", typeof(string));
    
            var sCampo8Parameter = sCampo8 != null ?
                new ObjectParameter("sCampo8", sCampo8) :
                new ObjectParameter("sCampo8", typeof(string));
    
            var sCo_Us_InParameter = sCo_Us_In != null ?
                new ObjectParameter("sCo_Us_In", sCo_Us_In) :
                new ObjectParameter("sCo_Us_In", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sRevisadoParameter = sRevisado != null ?
                new ObjectParameter("sRevisado", sRevisado) :
                new ObjectParameter("sRevisado", typeof(string));
    
            var sTrasnfeParameter = sTrasnfe != null ?
                new ObjectParameter("sTrasnfe", sTrasnfe) :
                new ObjectParameter("sTrasnfe", typeof(string));
    
            var sCo_Sucu_InParameter = sCo_Sucu_In != null ?
                new ObjectParameter("sCo_Sucu_In", sCo_Sucu_In) :
                new ObjectParameter("sCo_Sucu_In", typeof(string));
    
            var bJuridicoParameter = bJuridico.HasValue ?
                new ObjectParameter("bJuridico", bJuridico) :
                new ObjectParameter("bJuridico", typeof(bool));
    
            var iTipo_AdiParameter = iTipo_Adi.HasValue ?
                new ObjectParameter("iTipo_Adi", iTipo_Adi) :
                new ObjectParameter("iTipo_Adi", typeof(int));
    
            var sMatrizParameter = sMatriz != null ?
                new ObjectParameter("sMatriz", sMatriz) :
                new ObjectParameter("sMatriz", typeof(string));
    
            var sCo_TabParameter = sCo_Tab != null ?
                new ObjectParameter("sCo_Tab", sCo_Tab) :
                new ObjectParameter("sCo_Tab", typeof(string));
    
            var sTipo_PerParameter = sTipo_Per != null ?
                new ObjectParameter("sTipo_Per", sTipo_Per) :
                new ObjectParameter("sTipo_Per", typeof(string));
    
            var sCo_paisParameter = sCo_pais != null ?
                new ObjectParameter("sCo_pais", sCo_pais) :
                new ObjectParameter("sCo_pais", typeof(string));
    
            var sCiudadParameter = sCiudad != null ?
                new ObjectParameter("sCiudad", sCiudad) :
                new ObjectParameter("sCiudad", typeof(string));
    
            var sZipParameter = sZip != null ?
                new ObjectParameter("sZip", sZip) :
                new ObjectParameter("sZip", typeof(string));
    
            var sWebSiteParameter = sWebSite != null ?
                new ObjectParameter("sWebSite", sWebSite) :
                new ObjectParameter("sWebSite", typeof(string));
    
            var bContribu_EParameter = bContribu_E.HasValue ?
                new ObjectParameter("bContribu_E", bContribu_E) :
                new ObjectParameter("bContribu_E", typeof(bool));
    
            var bRete_Regis_DocParameter = bRete_Regis_Doc.HasValue ?
                new ObjectParameter("bRete_Regis_Doc", bRete_Regis_Doc) :
                new ObjectParameter("bRete_Regis_Doc", typeof(bool));
    
            var dePorc_EspParameter = dePorc_Esp.HasValue ?
                new ObjectParameter("dePorc_Esp", dePorc_Esp) :
                new ObjectParameter("dePorc_Esp", typeof(decimal));
    
            var sN_crParameter = sN_cr != null ?
                new ObjectParameter("sN_cr", sN_cr) :
                new ObjectParameter("sN_cr", typeof(string));
    
            var sN_dbParameter = sN_db != null ?
                new ObjectParameter("sN_db", sN_db) :
                new ObjectParameter("sN_db", typeof(string));
    
            var sTCompParameter = sTComp != null ?
                new ObjectParameter("sTComp", sTComp) :
                new ObjectParameter("sTComp", typeof(string));
    
            var sEmail_alternoParameter = sEmail_alterno != null ?
                new ObjectParameter("sEmail_alterno", sEmail_alterno) :
                new ObjectParameter("sEmail_alterno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pInsertarCliente_Result>("pInsertarCliente", sCo_CliParameter, sLoginParameter, sPasswordParameter, sSalesTaxParameter, sCli_DesParameter, sCo_segParameter, sCo_zonParameter, sCo_VenParameter, sEstadoParameter, bInactivoParameter, bValidoParameter, bSinCreditoParameter, bLunesParameter, bMartesParameter, bMiercolesParameter, bJuevesParameter, bViernesParameter, bSabadoParameter, bDomingoParameter, sDirec1Parameter, sDirec2Parameter, sDir_Ent2Parameter, sHorar_CajaParameter, sFrecu_VistParameter, sTelefonosParameter, sFaxParameter, sResponsParameter, sdFecha_regParameter, sTip_CliParameter, sSerialPParameter, iPuntajeParameter, iIdParameter, deMont_creParameter, sCo_moneParameter, sCond_PagParameter, iPlaz_pagParameter, deDesc_ppagoParameter, deDesc_GlobParameter, sTipo_IvaParameter, deIvaParameter, sRifParameter, bContribParameter, sDis_cenParameter, sNitParameter, sEmailParameter, sCo_Cta_Ingr_EgrParameter, sComentarioParameter, sCampo1Parameter, sCampo2Parameter, sCampo3Parameter, sCampo4Parameter, sCampo5Parameter, sCampo6Parameter, sCampo7Parameter, sCampo8Parameter, sCo_Us_InParameter, sMaquinaParameter, sRevisadoParameter, sTrasnfeParameter, sCo_Sucu_InParameter, bJuridicoParameter, iTipo_AdiParameter, sMatrizParameter, sCo_TabParameter, sTipo_PerParameter, sCo_paisParameter, sCiudadParameter, sZipParameter, sWebSiteParameter, bContribu_EParameter, bRete_Regis_DocParameter, dePorc_EspParameter, sN_crParameter, sN_dbParameter, sTCompParameter, sEmail_alternoParameter);
        }
    
        public virtual ObjectResult<pActualizarCliente_Result> pActualizarCliente(string sCo_Cli, string sCo_CliOri, string sLogin, string sPassword, string sSalesTax, string sCli_Des, string sCo_seg, string sCo_zon, string sCo_Ven, string sEstado, Nullable<bool> bInactivo, Nullable<bool> bValido, Nullable<bool> bSinCredito, Nullable<bool> bLunes, Nullable<bool> bMartes, Nullable<bool> bMiercoles, Nullable<bool> bJueves, Nullable<bool> bViernes, Nullable<bool> bSabado, Nullable<bool> bDomingo, string sDirec1, string sDirec2, string sDir_Ent2, string sHorar_Caja, string sFrecu_Vist, string sTelefonos, string sFax, string sRespons, Nullable<System.DateTime> sdFecha_reg, string sTip_Cli, string sSerialP, Nullable<int> iPuntaje, Nullable<int> iId, Nullable<decimal> deMont_cre, string sCo_Mone, string sCond_Pag, Nullable<int> iPlaz_pag, Nullable<decimal> deDesc_ppago, Nullable<decimal> deDesc_Glob, string sRif, Nullable<bool> bContrib, string sDis_cen, string sNit, string sEmail, string sCo_Cta_Ingr_Egr, string sComentario, string sCampo1, string sCampo2, string sCampo3, string sCampo4, string sCampo5, string sCampo6, string sCampo7, string sCampo8, string sCo_us_mo, string sCo_Sucu_Mo, string sMaquina, string sCampos, string sRevisado, string sTrasnfe, Nullable<bool> bJuridico, Nullable<int> iTipo_Adi, string sMatriz, string sCo_Tab, string sTipo_Per, string sCo_pais, string sCiudad, string sZip, string sWebSite, Nullable<bool> bContribu_E, Nullable<bool> bRete_Regis_Doc, Nullable<decimal> dePorc_Esp, byte[] tsValidador, Nullable<System.Guid> gRowguid, string sN_cr, string sN_db, string sTComp, string sEmail_alterno)
        {
            var sCo_CliParameter = sCo_Cli != null ?
                new ObjectParameter("sCo_Cli", sCo_Cli) :
                new ObjectParameter("sCo_Cli", typeof(string));
    
            var sCo_CliOriParameter = sCo_CliOri != null ?
                new ObjectParameter("sCo_CliOri", sCo_CliOri) :
                new ObjectParameter("sCo_CliOri", typeof(string));
    
            var sLoginParameter = sLogin != null ?
                new ObjectParameter("sLogin", sLogin) :
                new ObjectParameter("sLogin", typeof(string));
    
            var sPasswordParameter = sPassword != null ?
                new ObjectParameter("sPassword", sPassword) :
                new ObjectParameter("sPassword", typeof(string));
    
            var sSalesTaxParameter = sSalesTax != null ?
                new ObjectParameter("sSalesTax", sSalesTax) :
                new ObjectParameter("sSalesTax", typeof(string));
    
            var sCli_DesParameter = sCli_Des != null ?
                new ObjectParameter("sCli_Des", sCli_Des) :
                new ObjectParameter("sCli_Des", typeof(string));
    
            var sCo_segParameter = sCo_seg != null ?
                new ObjectParameter("sCo_seg", sCo_seg) :
                new ObjectParameter("sCo_seg", typeof(string));
    
            var sCo_zonParameter = sCo_zon != null ?
                new ObjectParameter("sCo_zon", sCo_zon) :
                new ObjectParameter("sCo_zon", typeof(string));
    
            var sCo_VenParameter = sCo_Ven != null ?
                new ObjectParameter("sCo_Ven", sCo_Ven) :
                new ObjectParameter("sCo_Ven", typeof(string));
    
            var sEstadoParameter = sEstado != null ?
                new ObjectParameter("sEstado", sEstado) :
                new ObjectParameter("sEstado", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var bValidoParameter = bValido.HasValue ?
                new ObjectParameter("bValido", bValido) :
                new ObjectParameter("bValido", typeof(bool));
    
            var bSinCreditoParameter = bSinCredito.HasValue ?
                new ObjectParameter("bSinCredito", bSinCredito) :
                new ObjectParameter("bSinCredito", typeof(bool));
    
            var bLunesParameter = bLunes.HasValue ?
                new ObjectParameter("bLunes", bLunes) :
                new ObjectParameter("bLunes", typeof(bool));
    
            var bMartesParameter = bMartes.HasValue ?
                new ObjectParameter("bMartes", bMartes) :
                new ObjectParameter("bMartes", typeof(bool));
    
            var bMiercolesParameter = bMiercoles.HasValue ?
                new ObjectParameter("bMiercoles", bMiercoles) :
                new ObjectParameter("bMiercoles", typeof(bool));
    
            var bJuevesParameter = bJueves.HasValue ?
                new ObjectParameter("bJueves", bJueves) :
                new ObjectParameter("bJueves", typeof(bool));
    
            var bViernesParameter = bViernes.HasValue ?
                new ObjectParameter("bViernes", bViernes) :
                new ObjectParameter("bViernes", typeof(bool));
    
            var bSabadoParameter = bSabado.HasValue ?
                new ObjectParameter("bSabado", bSabado) :
                new ObjectParameter("bSabado", typeof(bool));
    
            var bDomingoParameter = bDomingo.HasValue ?
                new ObjectParameter("bDomingo", bDomingo) :
                new ObjectParameter("bDomingo", typeof(bool));
    
            var sDirec1Parameter = sDirec1 != null ?
                new ObjectParameter("sDirec1", sDirec1) :
                new ObjectParameter("sDirec1", typeof(string));
    
            var sDirec2Parameter = sDirec2 != null ?
                new ObjectParameter("sDirec2", sDirec2) :
                new ObjectParameter("sDirec2", typeof(string));
    
            var sDir_Ent2Parameter = sDir_Ent2 != null ?
                new ObjectParameter("sDir_Ent2", sDir_Ent2) :
                new ObjectParameter("sDir_Ent2", typeof(string));
    
            var sHorar_CajaParameter = sHorar_Caja != null ?
                new ObjectParameter("sHorar_Caja", sHorar_Caja) :
                new ObjectParameter("sHorar_Caja", typeof(string));
    
            var sFrecu_VistParameter = sFrecu_Vist != null ?
                new ObjectParameter("sFrecu_Vist", sFrecu_Vist) :
                new ObjectParameter("sFrecu_Vist", typeof(string));
    
            var sTelefonosParameter = sTelefonos != null ?
                new ObjectParameter("sTelefonos", sTelefonos) :
                new ObjectParameter("sTelefonos", typeof(string));
    
            var sFaxParameter = sFax != null ?
                new ObjectParameter("sFax", sFax) :
                new ObjectParameter("sFax", typeof(string));
    
            var sResponsParameter = sRespons != null ?
                new ObjectParameter("sRespons", sRespons) :
                new ObjectParameter("sRespons", typeof(string));
    
            var sdFecha_regParameter = sdFecha_reg.HasValue ?
                new ObjectParameter("sdFecha_reg", sdFecha_reg) :
                new ObjectParameter("sdFecha_reg", typeof(System.DateTime));
    
            var sTip_CliParameter = sTip_Cli != null ?
                new ObjectParameter("sTip_Cli", sTip_Cli) :
                new ObjectParameter("sTip_Cli", typeof(string));
    
            var sSerialPParameter = sSerialP != null ?
                new ObjectParameter("sSerialP", sSerialP) :
                new ObjectParameter("sSerialP", typeof(string));
    
            var iPuntajeParameter = iPuntaje.HasValue ?
                new ObjectParameter("iPuntaje", iPuntaje) :
                new ObjectParameter("iPuntaje", typeof(int));
    
            var iIdParameter = iId.HasValue ?
                new ObjectParameter("iId", iId) :
                new ObjectParameter("iId", typeof(int));
    
            var deMont_creParameter = deMont_cre.HasValue ?
                new ObjectParameter("deMont_cre", deMont_cre) :
                new ObjectParameter("deMont_cre", typeof(decimal));
    
            var sCo_MoneParameter = sCo_Mone != null ?
                new ObjectParameter("sCo_Mone", sCo_Mone) :
                new ObjectParameter("sCo_Mone", typeof(string));
    
            var sCond_PagParameter = sCond_Pag != null ?
                new ObjectParameter("sCond_Pag", sCond_Pag) :
                new ObjectParameter("sCond_Pag", typeof(string));
    
            var iPlaz_pagParameter = iPlaz_pag.HasValue ?
                new ObjectParameter("iPlaz_pag", iPlaz_pag) :
                new ObjectParameter("iPlaz_pag", typeof(int));
    
            var deDesc_ppagoParameter = deDesc_ppago.HasValue ?
                new ObjectParameter("deDesc_ppago", deDesc_ppago) :
                new ObjectParameter("deDesc_ppago", typeof(decimal));
    
            var deDesc_GlobParameter = deDesc_Glob.HasValue ?
                new ObjectParameter("deDesc_Glob", deDesc_Glob) :
                new ObjectParameter("deDesc_Glob", typeof(decimal));
    
            var sRifParameter = sRif != null ?
                new ObjectParameter("sRif", sRif) :
                new ObjectParameter("sRif", typeof(string));
    
            var bContribParameter = bContrib.HasValue ?
                new ObjectParameter("bContrib", bContrib) :
                new ObjectParameter("bContrib", typeof(bool));
    
            var sDis_cenParameter = sDis_cen != null ?
                new ObjectParameter("sDis_cen", sDis_cen) :
                new ObjectParameter("sDis_cen", typeof(string));
    
            var sNitParameter = sNit != null ?
                new ObjectParameter("sNit", sNit) :
                new ObjectParameter("sNit", typeof(string));
    
            var sEmailParameter = sEmail != null ?
                new ObjectParameter("sEmail", sEmail) :
                new ObjectParameter("sEmail", typeof(string));
    
            var sCo_Cta_Ingr_EgrParameter = sCo_Cta_Ingr_Egr != null ?
                new ObjectParameter("sCo_Cta_Ingr_Egr", sCo_Cta_Ingr_Egr) :
                new ObjectParameter("sCo_Cta_Ingr_Egr", typeof(string));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var sCampo1Parameter = sCampo1 != null ?
                new ObjectParameter("sCampo1", sCampo1) :
                new ObjectParameter("sCampo1", typeof(string));
    
            var sCampo2Parameter = sCampo2 != null ?
                new ObjectParameter("sCampo2", sCampo2) :
                new ObjectParameter("sCampo2", typeof(string));
    
            var sCampo3Parameter = sCampo3 != null ?
                new ObjectParameter("sCampo3", sCampo3) :
                new ObjectParameter("sCampo3", typeof(string));
    
            var sCampo4Parameter = sCampo4 != null ?
                new ObjectParameter("sCampo4", sCampo4) :
                new ObjectParameter("sCampo4", typeof(string));
    
            var sCampo5Parameter = sCampo5 != null ?
                new ObjectParameter("sCampo5", sCampo5) :
                new ObjectParameter("sCampo5", typeof(string));
    
            var sCampo6Parameter = sCampo6 != null ?
                new ObjectParameter("sCampo6", sCampo6) :
                new ObjectParameter("sCampo6", typeof(string));
    
            var sCampo7Parameter = sCampo7 != null ?
                new ObjectParameter("sCampo7", sCampo7) :
                new ObjectParameter("sCampo7", typeof(string));
    
            var sCampo8Parameter = sCampo8 != null ?
                new ObjectParameter("sCampo8", sCampo8) :
                new ObjectParameter("sCampo8", typeof(string));
    
            var sCo_us_moParameter = sCo_us_mo != null ?
                new ObjectParameter("sCo_us_mo", sCo_us_mo) :
                new ObjectParameter("sCo_us_mo", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sCamposParameter = sCampos != null ?
                new ObjectParameter("sCampos", sCampos) :
                new ObjectParameter("sCampos", typeof(string));
    
            var sRevisadoParameter = sRevisado != null ?
                new ObjectParameter("sRevisado", sRevisado) :
                new ObjectParameter("sRevisado", typeof(string));
    
            var sTrasnfeParameter = sTrasnfe != null ?
                new ObjectParameter("sTrasnfe", sTrasnfe) :
                new ObjectParameter("sTrasnfe", typeof(string));
    
            var bJuridicoParameter = bJuridico.HasValue ?
                new ObjectParameter("bJuridico", bJuridico) :
                new ObjectParameter("bJuridico", typeof(bool));
    
            var iTipo_AdiParameter = iTipo_Adi.HasValue ?
                new ObjectParameter("iTipo_Adi", iTipo_Adi) :
                new ObjectParameter("iTipo_Adi", typeof(int));
    
            var sMatrizParameter = sMatriz != null ?
                new ObjectParameter("sMatriz", sMatriz) :
                new ObjectParameter("sMatriz", typeof(string));
    
            var sCo_TabParameter = sCo_Tab != null ?
                new ObjectParameter("sCo_Tab", sCo_Tab) :
                new ObjectParameter("sCo_Tab", typeof(string));
    
            var sTipo_PerParameter = sTipo_Per != null ?
                new ObjectParameter("sTipo_Per", sTipo_Per) :
                new ObjectParameter("sTipo_Per", typeof(string));
    
            var sCo_paisParameter = sCo_pais != null ?
                new ObjectParameter("sCo_pais", sCo_pais) :
                new ObjectParameter("sCo_pais", typeof(string));
    
            var sCiudadParameter = sCiudad != null ?
                new ObjectParameter("sCiudad", sCiudad) :
                new ObjectParameter("sCiudad", typeof(string));
    
            var sZipParameter = sZip != null ?
                new ObjectParameter("sZip", sZip) :
                new ObjectParameter("sZip", typeof(string));
    
            var sWebSiteParameter = sWebSite != null ?
                new ObjectParameter("sWebSite", sWebSite) :
                new ObjectParameter("sWebSite", typeof(string));
    
            var bContribu_EParameter = bContribu_E.HasValue ?
                new ObjectParameter("bContribu_E", bContribu_E) :
                new ObjectParameter("bContribu_E", typeof(bool));
    
            var bRete_Regis_DocParameter = bRete_Regis_Doc.HasValue ?
                new ObjectParameter("bRete_Regis_Doc", bRete_Regis_Doc) :
                new ObjectParameter("bRete_Regis_Doc", typeof(bool));
    
            var dePorc_EspParameter = dePorc_Esp.HasValue ?
                new ObjectParameter("dePorc_Esp", dePorc_Esp) :
                new ObjectParameter("dePorc_Esp", typeof(decimal));
    
            var tsValidadorParameter = tsValidador != null ?
                new ObjectParameter("tsValidador", tsValidador) :
                new ObjectParameter("tsValidador", typeof(byte[]));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            var sN_crParameter = sN_cr != null ?
                new ObjectParameter("sN_cr", sN_cr) :
                new ObjectParameter("sN_cr", typeof(string));
    
            var sN_dbParameter = sN_db != null ?
                new ObjectParameter("sN_db", sN_db) :
                new ObjectParameter("sN_db", typeof(string));
    
            var sTCompParameter = sTComp != null ?
                new ObjectParameter("sTComp", sTComp) :
                new ObjectParameter("sTComp", typeof(string));
    
            var sEmail_alternoParameter = sEmail_alterno != null ?
                new ObjectParameter("sEmail_alterno", sEmail_alterno) :
                new ObjectParameter("sEmail_alterno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pActualizarCliente_Result>("pActualizarCliente", sCo_CliParameter, sCo_CliOriParameter, sLoginParameter, sPasswordParameter, sSalesTaxParameter, sCli_DesParameter, sCo_segParameter, sCo_zonParameter, sCo_VenParameter, sEstadoParameter, bInactivoParameter, bValidoParameter, bSinCreditoParameter, bLunesParameter, bMartesParameter, bMiercolesParameter, bJuevesParameter, bViernesParameter, bSabadoParameter, bDomingoParameter, sDirec1Parameter, sDirec2Parameter, sDir_Ent2Parameter, sHorar_CajaParameter, sFrecu_VistParameter, sTelefonosParameter, sFaxParameter, sResponsParameter, sdFecha_regParameter, sTip_CliParameter, sSerialPParameter, iPuntajeParameter, iIdParameter, deMont_creParameter, sCo_MoneParameter, sCond_PagParameter, iPlaz_pagParameter, deDesc_ppagoParameter, deDesc_GlobParameter, sRifParameter, bContribParameter, sDis_cenParameter, sNitParameter, sEmailParameter, sCo_Cta_Ingr_EgrParameter, sComentarioParameter, sCampo1Parameter, sCampo2Parameter, sCampo3Parameter, sCampo4Parameter, sCampo5Parameter, sCampo6Parameter, sCampo7Parameter, sCampo8Parameter, sCo_us_moParameter, sCo_Sucu_MoParameter, sMaquinaParameter, sCamposParameter, sRevisadoParameter, sTrasnfeParameter, bJuridicoParameter, iTipo_AdiParameter, sMatrizParameter, sCo_TabParameter, sTipo_PerParameter, sCo_paisParameter, sCiudadParameter, sZipParameter, sWebSiteParameter, bContribu_EParameter, bRete_Regis_DocParameter, dePorc_EspParameter, tsValidadorParameter, gRowguidParameter, sN_crParameter, sN_dbParameter, sTCompParameter, sEmail_alternoParameter);
        }
    
        public virtual int pEliminarCliente(string sCo_CliOri, byte[] tsValidador, string sMaquina, string sCo_Us_Mo, string sCo_Sucu_Mo, Nullable<System.Guid> gRowguid)
        {
            var sCo_CliOriParameter = sCo_CliOri != null ?
                new ObjectParameter("sCo_CliOri", sCo_CliOri) :
                new ObjectParameter("sCo_CliOri", typeof(string));
    
            var tsValidadorParameter = tsValidador != null ?
                new ObjectParameter("tsValidador", tsValidador) :
                new ObjectParameter("tsValidador", typeof(byte[]));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sCo_Us_MoParameter = sCo_Us_Mo != null ?
                new ObjectParameter("sCo_Us_Mo", sCo_Us_Mo) :
                new ObjectParameter("sCo_Us_Mo", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pEliminarCliente", sCo_CliOriParameter, tsValidadorParameter, sMaquinaParameter, sCo_Us_MoParameter, sCo_Sucu_MoParameter, gRowguidParameter);
        }
    
        public virtual ObjectResult<pActualizarProveedor_Result> pActualizarProveedor(string sCo_Prov, string sCo_ProvOri, string sProv_des, string sCo_seg, string sCo_zon, Nullable<bool> bInactivo, string sDirec1, string sDirec2, string sTelefonos, string sFax, string sRespons, Nullable<System.DateTime> sdFecha_reg, string sTip_Pro, Nullable<decimal> deMont_cre, string sCo_Mone, string sCond_Pag, Nullable<int> iPlaz_pag, Nullable<decimal> deDesc_ppago, Nullable<decimal> deDesc_Glob, string sRif, Nullable<bool> bNacional, string sDis_cen, string sNit, string sEmail, string sCo_Cta_Ingr_Egr, string sComentario, Nullable<int> iTipo_Adi, string sMatriz, string sCo_Tab, string sTipo_Per, string sCo_pais, string sCiudad, string sZip, string sWebSite, string sFormType, string sTaxid, Nullable<bool> bContribu_E, Nullable<bool> bRete_Regis_Doc, Nullable<decimal> dePorc_Esp, string sCampo1, string sCampo2, string sCampo3, string sCampo4, string sCampo5, string sCampo6, string sCampo7, string sCampo8, string sCo_Us_Mo, string sCo_Sucu_Mo, string sMaquina, string sCampos, string sRevisado, string sTrasnfe, byte[] tsValidador, Nullable<System.Guid> gRowguid, string sTgasto, string sTComp, string sEmail_alterno, Nullable<bool> bSujeto_Obj_RetenISLR_Auto)
        {
            var sCo_ProvParameter = sCo_Prov != null ?
                new ObjectParameter("sCo_Prov", sCo_Prov) :
                new ObjectParameter("sCo_Prov", typeof(string));
    
            var sCo_ProvOriParameter = sCo_ProvOri != null ?
                new ObjectParameter("sCo_ProvOri", sCo_ProvOri) :
                new ObjectParameter("sCo_ProvOri", typeof(string));
    
            var sProv_desParameter = sProv_des != null ?
                new ObjectParameter("sProv_des", sProv_des) :
                new ObjectParameter("sProv_des", typeof(string));
    
            var sCo_segParameter = sCo_seg != null ?
                new ObjectParameter("sCo_seg", sCo_seg) :
                new ObjectParameter("sCo_seg", typeof(string));
    
            var sCo_zonParameter = sCo_zon != null ?
                new ObjectParameter("sCo_zon", sCo_zon) :
                new ObjectParameter("sCo_zon", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var sDirec1Parameter = sDirec1 != null ?
                new ObjectParameter("sDirec1", sDirec1) :
                new ObjectParameter("sDirec1", typeof(string));
    
            var sDirec2Parameter = sDirec2 != null ?
                new ObjectParameter("sDirec2", sDirec2) :
                new ObjectParameter("sDirec2", typeof(string));
    
            var sTelefonosParameter = sTelefonos != null ?
                new ObjectParameter("sTelefonos", sTelefonos) :
                new ObjectParameter("sTelefonos", typeof(string));
    
            var sFaxParameter = sFax != null ?
                new ObjectParameter("sFax", sFax) :
                new ObjectParameter("sFax", typeof(string));
    
            var sResponsParameter = sRespons != null ?
                new ObjectParameter("sRespons", sRespons) :
                new ObjectParameter("sRespons", typeof(string));
    
            var sdFecha_regParameter = sdFecha_reg.HasValue ?
                new ObjectParameter("sdFecha_reg", sdFecha_reg) :
                new ObjectParameter("sdFecha_reg", typeof(System.DateTime));
    
            var sTip_ProParameter = sTip_Pro != null ?
                new ObjectParameter("sTip_Pro", sTip_Pro) :
                new ObjectParameter("sTip_Pro", typeof(string));
    
            var deMont_creParameter = deMont_cre.HasValue ?
                new ObjectParameter("deMont_cre", deMont_cre) :
                new ObjectParameter("deMont_cre", typeof(decimal));
    
            var sCo_MoneParameter = sCo_Mone != null ?
                new ObjectParameter("sCo_Mone", sCo_Mone) :
                new ObjectParameter("sCo_Mone", typeof(string));
    
            var sCond_PagParameter = sCond_Pag != null ?
                new ObjectParameter("sCond_Pag", sCond_Pag) :
                new ObjectParameter("sCond_Pag", typeof(string));
    
            var iPlaz_pagParameter = iPlaz_pag.HasValue ?
                new ObjectParameter("iPlaz_pag", iPlaz_pag) :
                new ObjectParameter("iPlaz_pag", typeof(int));
    
            var deDesc_ppagoParameter = deDesc_ppago.HasValue ?
                new ObjectParameter("deDesc_ppago", deDesc_ppago) :
                new ObjectParameter("deDesc_ppago", typeof(decimal));
    
            var deDesc_GlobParameter = deDesc_Glob.HasValue ?
                new ObjectParameter("deDesc_Glob", deDesc_Glob) :
                new ObjectParameter("deDesc_Glob", typeof(decimal));
    
            var sRifParameter = sRif != null ?
                new ObjectParameter("sRif", sRif) :
                new ObjectParameter("sRif", typeof(string));
    
            var bNacionalParameter = bNacional.HasValue ?
                new ObjectParameter("bNacional", bNacional) :
                new ObjectParameter("bNacional", typeof(bool));
    
            var sDis_cenParameter = sDis_cen != null ?
                new ObjectParameter("sDis_cen", sDis_cen) :
                new ObjectParameter("sDis_cen", typeof(string));
    
            var sNitParameter = sNit != null ?
                new ObjectParameter("sNit", sNit) :
                new ObjectParameter("sNit", typeof(string));
    
            var sEmailParameter = sEmail != null ?
                new ObjectParameter("sEmail", sEmail) :
                new ObjectParameter("sEmail", typeof(string));
    
            var sCo_Cta_Ingr_EgrParameter = sCo_Cta_Ingr_Egr != null ?
                new ObjectParameter("sCo_Cta_Ingr_Egr", sCo_Cta_Ingr_Egr) :
                new ObjectParameter("sCo_Cta_Ingr_Egr", typeof(string));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var iTipo_AdiParameter = iTipo_Adi.HasValue ?
                new ObjectParameter("iTipo_Adi", iTipo_Adi) :
                new ObjectParameter("iTipo_Adi", typeof(int));
    
            var sMatrizParameter = sMatriz != null ?
                new ObjectParameter("sMatriz", sMatriz) :
                new ObjectParameter("sMatriz", typeof(string));
    
            var sCo_TabParameter = sCo_Tab != null ?
                new ObjectParameter("sCo_Tab", sCo_Tab) :
                new ObjectParameter("sCo_Tab", typeof(string));
    
            var sTipo_PerParameter = sTipo_Per != null ?
                new ObjectParameter("sTipo_Per", sTipo_Per) :
                new ObjectParameter("sTipo_Per", typeof(string));
    
            var sCo_paisParameter = sCo_pais != null ?
                new ObjectParameter("sCo_pais", sCo_pais) :
                new ObjectParameter("sCo_pais", typeof(string));
    
            var sCiudadParameter = sCiudad != null ?
                new ObjectParameter("sCiudad", sCiudad) :
                new ObjectParameter("sCiudad", typeof(string));
    
            var sZipParameter = sZip != null ?
                new ObjectParameter("sZip", sZip) :
                new ObjectParameter("sZip", typeof(string));
    
            var sWebSiteParameter = sWebSite != null ?
                new ObjectParameter("sWebSite", sWebSite) :
                new ObjectParameter("sWebSite", typeof(string));
    
            var sFormTypeParameter = sFormType != null ?
                new ObjectParameter("sFormType", sFormType) :
                new ObjectParameter("sFormType", typeof(string));
    
            var sTaxidParameter = sTaxid != null ?
                new ObjectParameter("sTaxid", sTaxid) :
                new ObjectParameter("sTaxid", typeof(string));
    
            var bContribu_EParameter = bContribu_E.HasValue ?
                new ObjectParameter("bContribu_E", bContribu_E) :
                new ObjectParameter("bContribu_E", typeof(bool));
    
            var bRete_Regis_DocParameter = bRete_Regis_Doc.HasValue ?
                new ObjectParameter("bRete_Regis_Doc", bRete_Regis_Doc) :
                new ObjectParameter("bRete_Regis_Doc", typeof(bool));
    
            var dePorc_EspParameter = dePorc_Esp.HasValue ?
                new ObjectParameter("dePorc_Esp", dePorc_Esp) :
                new ObjectParameter("dePorc_Esp", typeof(decimal));
    
            var sCampo1Parameter = sCampo1 != null ?
                new ObjectParameter("sCampo1", sCampo1) :
                new ObjectParameter("sCampo1", typeof(string));
    
            var sCampo2Parameter = sCampo2 != null ?
                new ObjectParameter("sCampo2", sCampo2) :
                new ObjectParameter("sCampo2", typeof(string));
    
            var sCampo3Parameter = sCampo3 != null ?
                new ObjectParameter("sCampo3", sCampo3) :
                new ObjectParameter("sCampo3", typeof(string));
    
            var sCampo4Parameter = sCampo4 != null ?
                new ObjectParameter("sCampo4", sCampo4) :
                new ObjectParameter("sCampo4", typeof(string));
    
            var sCampo5Parameter = sCampo5 != null ?
                new ObjectParameter("sCampo5", sCampo5) :
                new ObjectParameter("sCampo5", typeof(string));
    
            var sCampo6Parameter = sCampo6 != null ?
                new ObjectParameter("sCampo6", sCampo6) :
                new ObjectParameter("sCampo6", typeof(string));
    
            var sCampo7Parameter = sCampo7 != null ?
                new ObjectParameter("sCampo7", sCampo7) :
                new ObjectParameter("sCampo7", typeof(string));
    
            var sCampo8Parameter = sCampo8 != null ?
                new ObjectParameter("sCampo8", sCampo8) :
                new ObjectParameter("sCampo8", typeof(string));
    
            var sCo_Us_MoParameter = sCo_Us_Mo != null ?
                new ObjectParameter("sCo_Us_Mo", sCo_Us_Mo) :
                new ObjectParameter("sCo_Us_Mo", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sCamposParameter = sCampos != null ?
                new ObjectParameter("sCampos", sCampos) :
                new ObjectParameter("sCampos", typeof(string));
    
            var sRevisadoParameter = sRevisado != null ?
                new ObjectParameter("sRevisado", sRevisado) :
                new ObjectParameter("sRevisado", typeof(string));
    
            var sTrasnfeParameter = sTrasnfe != null ?
                new ObjectParameter("sTrasnfe", sTrasnfe) :
                new ObjectParameter("sTrasnfe", typeof(string));
    
            var tsValidadorParameter = tsValidador != null ?
                new ObjectParameter("tsValidador", tsValidador) :
                new ObjectParameter("tsValidador", typeof(byte[]));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            var sTgastoParameter = sTgasto != null ?
                new ObjectParameter("sTgasto", sTgasto) :
                new ObjectParameter("sTgasto", typeof(string));
    
            var sTCompParameter = sTComp != null ?
                new ObjectParameter("sTComp", sTComp) :
                new ObjectParameter("sTComp", typeof(string));
    
            var sEmail_alternoParameter = sEmail_alterno != null ?
                new ObjectParameter("sEmail_alterno", sEmail_alterno) :
                new ObjectParameter("sEmail_alterno", typeof(string));
    
            var bSujeto_Obj_RetenISLR_AutoParameter = bSujeto_Obj_RetenISLR_Auto.HasValue ?
                new ObjectParameter("bSujeto_Obj_RetenISLR_Auto", bSujeto_Obj_RetenISLR_Auto) :
                new ObjectParameter("bSujeto_Obj_RetenISLR_Auto", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pActualizarProveedor_Result>("pActualizarProveedor", sCo_ProvParameter, sCo_ProvOriParameter, sProv_desParameter, sCo_segParameter, sCo_zonParameter, bInactivoParameter, sDirec1Parameter, sDirec2Parameter, sTelefonosParameter, sFaxParameter, sResponsParameter, sdFecha_regParameter, sTip_ProParameter, deMont_creParameter, sCo_MoneParameter, sCond_PagParameter, iPlaz_pagParameter, deDesc_ppagoParameter, deDesc_GlobParameter, sRifParameter, bNacionalParameter, sDis_cenParameter, sNitParameter, sEmailParameter, sCo_Cta_Ingr_EgrParameter, sComentarioParameter, iTipo_AdiParameter, sMatrizParameter, sCo_TabParameter, sTipo_PerParameter, sCo_paisParameter, sCiudadParameter, sZipParameter, sWebSiteParameter, sFormTypeParameter, sTaxidParameter, bContribu_EParameter, bRete_Regis_DocParameter, dePorc_EspParameter, sCampo1Parameter, sCampo2Parameter, sCampo3Parameter, sCampo4Parameter, sCampo5Parameter, sCampo6Parameter, sCampo7Parameter, sCampo8Parameter, sCo_Us_MoParameter, sCo_Sucu_MoParameter, sMaquinaParameter, sCamposParameter, sRevisadoParameter, sTrasnfeParameter, tsValidadorParameter, gRowguidParameter, sTgastoParameter, sTCompParameter, sEmail_alternoParameter, bSujeto_Obj_RetenISLR_AutoParameter);
        }
    
        public virtual int pEliminarProveedor(string sCo_ProvOri, byte[] tsValidador, string sMaquina, string sCo_Us_Mo, string sCo_Sucu_Mo, Nullable<System.Guid> gRowguid)
        {
            var sCo_ProvOriParameter = sCo_ProvOri != null ?
                new ObjectParameter("sCo_ProvOri", sCo_ProvOri) :
                new ObjectParameter("sCo_ProvOri", typeof(string));
    
            var tsValidadorParameter = tsValidador != null ?
                new ObjectParameter("tsValidador", tsValidador) :
                new ObjectParameter("tsValidador", typeof(byte[]));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sCo_Us_MoParameter = sCo_Us_Mo != null ?
                new ObjectParameter("sCo_Us_Mo", sCo_Us_Mo) :
                new ObjectParameter("sCo_Us_Mo", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pEliminarProveedor", sCo_ProvOriParameter, tsValidadorParameter, sMaquinaParameter, sCo_Us_MoParameter, sCo_Sucu_MoParameter, gRowguidParameter);
        }
    
        public virtual ObjectResult<pInsertarProveedor_Result> pInsertarProveedor(string sCo_Prov, string sProv_des, string sCo_seg, string sCo_zon, Nullable<bool> bInactivo, string sDirec1, string sDirec2, string sTelefonos, string sFax, string sRespons, Nullable<System.DateTime> sdFecha_reg, string sTip_Pro, Nullable<decimal> deMont_cre, string sCo_Mone, string sCond_Pag, Nullable<int> iPlaz_pag, Nullable<decimal> deDesc_ppago, Nullable<decimal> deDesc_Glob, string sRif, Nullable<bool> bNacional, string sDis_cen, string sNit, string sEmail, string sCo_Cta_Ingr_Egr, string sComentario, Nullable<int> iTipo_Adi, string sMatriz, string sCo_Tab, string sTipo_Per, string sCo_pais, string sCiudad, string sZip, string sWebSite, string sFormType, string sTaxid, Nullable<bool> bContribu_E, Nullable<bool> bRete_Regis_Doc, Nullable<decimal> dePorc_Esp, string sCampo1, string sCampo2, string sCampo3, string sCampo4, string sCampo5, string sCampo6, string sCampo7, string sCampo8, string sCo_Us_In, string sCo_Sucu_In, string sMaquina, string sRevisado, string sTrasnfe, string sTgasto, string sTComp, string sEmail_alterno, Nullable<bool> bSujeto_Obj_RetenISLR_Auto)
        {
            var sCo_ProvParameter = sCo_Prov != null ?
                new ObjectParameter("sCo_Prov", sCo_Prov) :
                new ObjectParameter("sCo_Prov", typeof(string));
    
            var sProv_desParameter = sProv_des != null ?
                new ObjectParameter("sProv_des", sProv_des) :
                new ObjectParameter("sProv_des", typeof(string));
    
            var sCo_segParameter = sCo_seg != null ?
                new ObjectParameter("sCo_seg", sCo_seg) :
                new ObjectParameter("sCo_seg", typeof(string));
    
            var sCo_zonParameter = sCo_zon != null ?
                new ObjectParameter("sCo_zon", sCo_zon) :
                new ObjectParameter("sCo_zon", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var sDirec1Parameter = sDirec1 != null ?
                new ObjectParameter("sDirec1", sDirec1) :
                new ObjectParameter("sDirec1", typeof(string));
    
            var sDirec2Parameter = sDirec2 != null ?
                new ObjectParameter("sDirec2", sDirec2) :
                new ObjectParameter("sDirec2", typeof(string));
    
            var sTelefonosParameter = sTelefonos != null ?
                new ObjectParameter("sTelefonos", sTelefonos) :
                new ObjectParameter("sTelefonos", typeof(string));
    
            var sFaxParameter = sFax != null ?
                new ObjectParameter("sFax", sFax) :
                new ObjectParameter("sFax", typeof(string));
    
            var sResponsParameter = sRespons != null ?
                new ObjectParameter("sRespons", sRespons) :
                new ObjectParameter("sRespons", typeof(string));
    
            var sdFecha_regParameter = sdFecha_reg.HasValue ?
                new ObjectParameter("sdFecha_reg", sdFecha_reg) :
                new ObjectParameter("sdFecha_reg", typeof(System.DateTime));
    
            var sTip_ProParameter = sTip_Pro != null ?
                new ObjectParameter("sTip_Pro", sTip_Pro) :
                new ObjectParameter("sTip_Pro", typeof(string));
    
            var deMont_creParameter = deMont_cre.HasValue ?
                new ObjectParameter("deMont_cre", deMont_cre) :
                new ObjectParameter("deMont_cre", typeof(decimal));
    
            var sCo_MoneParameter = sCo_Mone != null ?
                new ObjectParameter("sCo_Mone", sCo_Mone) :
                new ObjectParameter("sCo_Mone", typeof(string));
    
            var sCond_PagParameter = sCond_Pag != null ?
                new ObjectParameter("sCond_Pag", sCond_Pag) :
                new ObjectParameter("sCond_Pag", typeof(string));
    
            var iPlaz_pagParameter = iPlaz_pag.HasValue ?
                new ObjectParameter("iPlaz_pag", iPlaz_pag) :
                new ObjectParameter("iPlaz_pag", typeof(int));
    
            var deDesc_ppagoParameter = deDesc_ppago.HasValue ?
                new ObjectParameter("deDesc_ppago", deDesc_ppago) :
                new ObjectParameter("deDesc_ppago", typeof(decimal));
    
            var deDesc_GlobParameter = deDesc_Glob.HasValue ?
                new ObjectParameter("deDesc_Glob", deDesc_Glob) :
                new ObjectParameter("deDesc_Glob", typeof(decimal));
    
            var sRifParameter = sRif != null ?
                new ObjectParameter("sRif", sRif) :
                new ObjectParameter("sRif", typeof(string));
    
            var bNacionalParameter = bNacional.HasValue ?
                new ObjectParameter("bNacional", bNacional) :
                new ObjectParameter("bNacional", typeof(bool));
    
            var sDis_cenParameter = sDis_cen != null ?
                new ObjectParameter("sDis_cen", sDis_cen) :
                new ObjectParameter("sDis_cen", typeof(string));
    
            var sNitParameter = sNit != null ?
                new ObjectParameter("sNit", sNit) :
                new ObjectParameter("sNit", typeof(string));
    
            var sEmailParameter = sEmail != null ?
                new ObjectParameter("sEmail", sEmail) :
                new ObjectParameter("sEmail", typeof(string));
    
            var sCo_Cta_Ingr_EgrParameter = sCo_Cta_Ingr_Egr != null ?
                new ObjectParameter("sCo_Cta_Ingr_Egr", sCo_Cta_Ingr_Egr) :
                new ObjectParameter("sCo_Cta_Ingr_Egr", typeof(string));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var iTipo_AdiParameter = iTipo_Adi.HasValue ?
                new ObjectParameter("iTipo_Adi", iTipo_Adi) :
                new ObjectParameter("iTipo_Adi", typeof(int));
    
            var sMatrizParameter = sMatriz != null ?
                new ObjectParameter("sMatriz", sMatriz) :
                new ObjectParameter("sMatriz", typeof(string));
    
            var sCo_TabParameter = sCo_Tab != null ?
                new ObjectParameter("sCo_Tab", sCo_Tab) :
                new ObjectParameter("sCo_Tab", typeof(string));
    
            var sTipo_PerParameter = sTipo_Per != null ?
                new ObjectParameter("sTipo_Per", sTipo_Per) :
                new ObjectParameter("sTipo_Per", typeof(string));
    
            var sCo_paisParameter = sCo_pais != null ?
                new ObjectParameter("sCo_pais", sCo_pais) :
                new ObjectParameter("sCo_pais", typeof(string));
    
            var sCiudadParameter = sCiudad != null ?
                new ObjectParameter("sCiudad", sCiudad) :
                new ObjectParameter("sCiudad", typeof(string));
    
            var sZipParameter = sZip != null ?
                new ObjectParameter("sZip", sZip) :
                new ObjectParameter("sZip", typeof(string));
    
            var sWebSiteParameter = sWebSite != null ?
                new ObjectParameter("sWebSite", sWebSite) :
                new ObjectParameter("sWebSite", typeof(string));
    
            var sFormTypeParameter = sFormType != null ?
                new ObjectParameter("sFormType", sFormType) :
                new ObjectParameter("sFormType", typeof(string));
    
            var sTaxidParameter = sTaxid != null ?
                new ObjectParameter("sTaxid", sTaxid) :
                new ObjectParameter("sTaxid", typeof(string));
    
            var bContribu_EParameter = bContribu_E.HasValue ?
                new ObjectParameter("bContribu_E", bContribu_E) :
                new ObjectParameter("bContribu_E", typeof(bool));
    
            var bRete_Regis_DocParameter = bRete_Regis_Doc.HasValue ?
                new ObjectParameter("bRete_Regis_Doc", bRete_Regis_Doc) :
                new ObjectParameter("bRete_Regis_Doc", typeof(bool));
    
            var dePorc_EspParameter = dePorc_Esp.HasValue ?
                new ObjectParameter("dePorc_Esp", dePorc_Esp) :
                new ObjectParameter("dePorc_Esp", typeof(decimal));
    
            var sCampo1Parameter = sCampo1 != null ?
                new ObjectParameter("sCampo1", sCampo1) :
                new ObjectParameter("sCampo1", typeof(string));
    
            var sCampo2Parameter = sCampo2 != null ?
                new ObjectParameter("sCampo2", sCampo2) :
                new ObjectParameter("sCampo2", typeof(string));
    
            var sCampo3Parameter = sCampo3 != null ?
                new ObjectParameter("sCampo3", sCampo3) :
                new ObjectParameter("sCampo3", typeof(string));
    
            var sCampo4Parameter = sCampo4 != null ?
                new ObjectParameter("sCampo4", sCampo4) :
                new ObjectParameter("sCampo4", typeof(string));
    
            var sCampo5Parameter = sCampo5 != null ?
                new ObjectParameter("sCampo5", sCampo5) :
                new ObjectParameter("sCampo5", typeof(string));
    
            var sCampo6Parameter = sCampo6 != null ?
                new ObjectParameter("sCampo6", sCampo6) :
                new ObjectParameter("sCampo6", typeof(string));
    
            var sCampo7Parameter = sCampo7 != null ?
                new ObjectParameter("sCampo7", sCampo7) :
                new ObjectParameter("sCampo7", typeof(string));
    
            var sCampo8Parameter = sCampo8 != null ?
                new ObjectParameter("sCampo8", sCampo8) :
                new ObjectParameter("sCampo8", typeof(string));
    
            var sCo_Us_InParameter = sCo_Us_In != null ?
                new ObjectParameter("sCo_Us_In", sCo_Us_In) :
                new ObjectParameter("sCo_Us_In", typeof(string));
    
            var sCo_Sucu_InParameter = sCo_Sucu_In != null ?
                new ObjectParameter("sCo_Sucu_In", sCo_Sucu_In) :
                new ObjectParameter("sCo_Sucu_In", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sRevisadoParameter = sRevisado != null ?
                new ObjectParameter("sRevisado", sRevisado) :
                new ObjectParameter("sRevisado", typeof(string));
    
            var sTrasnfeParameter = sTrasnfe != null ?
                new ObjectParameter("sTrasnfe", sTrasnfe) :
                new ObjectParameter("sTrasnfe", typeof(string));
    
            var sTgastoParameter = sTgasto != null ?
                new ObjectParameter("sTgasto", sTgasto) :
                new ObjectParameter("sTgasto", typeof(string));
    
            var sTCompParameter = sTComp != null ?
                new ObjectParameter("sTComp", sTComp) :
                new ObjectParameter("sTComp", typeof(string));
    
            var sEmail_alternoParameter = sEmail_alterno != null ?
                new ObjectParameter("sEmail_alterno", sEmail_alterno) :
                new ObjectParameter("sEmail_alterno", typeof(string));
    
            var bSujeto_Obj_RetenISLR_AutoParameter = bSujeto_Obj_RetenISLR_Auto.HasValue ?
                new ObjectParameter("bSujeto_Obj_RetenISLR_Auto", bSujeto_Obj_RetenISLR_Auto) :
                new ObjectParameter("bSujeto_Obj_RetenISLR_Auto", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pInsertarProveedor_Result>("pInsertarProveedor", sCo_ProvParameter, sProv_desParameter, sCo_segParameter, sCo_zonParameter, bInactivoParameter, sDirec1Parameter, sDirec2Parameter, sTelefonosParameter, sFaxParameter, sResponsParameter, sdFecha_regParameter, sTip_ProParameter, deMont_creParameter, sCo_MoneParameter, sCond_PagParameter, iPlaz_pagParameter, deDesc_ppagoParameter, deDesc_GlobParameter, sRifParameter, bNacionalParameter, sDis_cenParameter, sNitParameter, sEmailParameter, sCo_Cta_Ingr_EgrParameter, sComentarioParameter, iTipo_AdiParameter, sMatrizParameter, sCo_TabParameter, sTipo_PerParameter, sCo_paisParameter, sCiudadParameter, sZipParameter, sWebSiteParameter, sFormTypeParameter, sTaxidParameter, bContribu_EParameter, bRete_Regis_DocParameter, dePorc_EspParameter, sCampo1Parameter, sCampo2Parameter, sCampo3Parameter, sCampo4Parameter, sCampo5Parameter, sCampo6Parameter, sCampo7Parameter, sCampo8Parameter, sCo_Us_InParameter, sCo_Sucu_InParameter, sMaquinaParameter, sRevisadoParameter, sTrasnfeParameter, sTgastoParameter, sTCompParameter, sEmail_alternoParameter, bSujeto_Obj_RetenISLR_AutoParameter);
        }
    }
}
