//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvParEmp
    {
        public string cod_emp { get; set; }
        public string cod_usu { get; set; }
        public string co_cta_ingr_egr { get; set; }
        public string co_cta_ingr_egr_FacDev { get; set; }
        public string cod_caja { get; set; }
        public bool tf_vendedor { get; set; }
        public bool tf_num_turno { get; set; }
        public bool tf_consecutivos { get; set; }
        public bool tf_caja { get; set; }
        public bool tf_sucursal { get; set; }
        public bool tf_cajero { get; set; }
        public bool tf_num_items { get; set; }
        public bool man_turno { get; set; }
        public bool manejo_identificadores { get; set; }
        public string co_imagen { get; set; }
        public string descrip_imagen { get; set; }
        public bool uso_ncr { get; set; }
        public bool fp_efectivo { get; set; }
        public bool fp_vale { get; set; }
        public bool fp_cheque { get; set; }
        public bool fp_tarjd { get; set; }
        public bool fp_tarjc { get; set; }
        public Nullable<decimal> monto_max_vuelto { get; set; }
        public Nullable<decimal> monto_min_cheque { get; set; }
        public Nullable<decimal> monto_min_tarjd { get; set; }
        public Nullable<decimal> monto_min_tarjc { get; set; }
        public bool dev_efectivo { get; set; }
        public bool dev_cheque { get; set; }
        public bool dev_tarjeta { get; set; }
        public bool dev_ncr { get; set; }
        public bool dev_vale { get; set; }
        public string expre_reg_telef_val { get; set; }
        public string expre_reg_telef_ejm { get; set; }
        public string expre_reg_email_val { get; set; }
        public string expre_reg_email_ejm { get; set; }
        public string tipo_cliente { get; set; }
        public string etiqueta_impuesto { get; set; }
        public string logo_empresa { get; set; }
        public bool autoriza_dev_efect { get; set; }
        public Nullable<int> dias_max_dev { get; set; }
        public Nullable<decimal> monto_min_dev { get; set; }
        public Nullable<decimal> monto_max_dev { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<bool> fp_efectivo_moneda2 { get; set; }
        public Nullable<bool> uso_ncr_moneda2 { get; set; }
        public Nullable<bool> fp_cheque_moneda2 { get; set; }
        public Nullable<decimal> monto_min_cheque_moneda2 { get; set; }
        public Nullable<bool> fp_tarjd_moneda2 { get; set; }
        public Nullable<decimal> monto_min_tarjd_moneda2 { get; set; }
        public Nullable<bool> fp_deposito_moneda2 { get; set; }
        public Nullable<decimal> monto_min_deposito_moneda2 { get; set; }
        public Nullable<bool> fp_transferencia_moneda2 { get; set; }
        public Nullable<decimal> monto_min_transferencia_moneda2 { get; set; }
        public Nullable<bool> fp_tarjc_moneda2 { get; set; }
        public Nullable<decimal> monto_min_tarjc_moneda2 { get; set; }
        public Nullable<bool> fp_vale_moneda2 { get; set; }
        public Nullable<decimal> monto_max_vuelto_moneda2 { get; set; }
        public string cod_caja_moneda2 { get; set; }
        public string co_cta_ingr_egr_moneda2 { get; set; }
        public string co_cta_ingr_egr_facdev_moneda2 { get; set; }
        public string co_cta_ingr_egr_banco_moneda2 { get; set; }
        public string co_Mone_moneda2 { get; set; }
        public Nullable<bool> fp_efectivo_moneda3 { get; set; }
        public Nullable<bool> uso_ncr_moneda3 { get; set; }
        public Nullable<bool> fp_cheque_moneda3 { get; set; }
        public Nullable<decimal> monto_min_cheque_moneda3 { get; set; }
        public Nullable<bool> fp_tarjd_moneda3 { get; set; }
        public Nullable<decimal> monto_min_tarjd_moneda3 { get; set; }
        public Nullable<bool> fp_deposito_moneda3 { get; set; }
        public Nullable<decimal> monto_min_deposito_moneda3 { get; set; }
        public Nullable<bool> fp_transferencia_moneda3 { get; set; }
        public Nullable<decimal> monto_min_transferencia_moneda3 { get; set; }
        public Nullable<bool> fp_tarjc_moneda3 { get; set; }
        public Nullable<decimal> monto_min_tarjc_moneda3 { get; set; }
        public Nullable<bool> fp_vale_moneda3 { get; set; }
        public Nullable<decimal> monto_max_vuelto_moneda3 { get; set; }
        public string cod_caja_moneda3 { get; set; }
        public string co_cta_ingr_egr_moneda3 { get; set; }
        public string co_cta_ingr_egr_facdev_moneda3 { get; set; }
        public string co_cta_ingr_egr_banco_moneda3 { get; set; }
        public string co_Mone_moneda3 { get; set; }
        public bool fp_deposito { get; set; }
        public bool fp_transferencia { get; set; }
        public Nullable<decimal> monto_min_deposito { get; set; }
        public Nullable<decimal> monto_min_transferencia { get; set; }
        public string co_cta_ingr_egr_banco { get; set; }
    
        public virtual saCaja saCaja { get; set; }
        public virtual saCaja saCaja1 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr1 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr2 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr3 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr4 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr5 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr6 { get; set; }
        public virtual saCaja saCaja2 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr7 { get; set; }
    }
}
