//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string FormatReport { get; set; }
        public bool IsEnabled { get; set; }
        public int GroupID { get; set; }
    
        public virtual GroupReports GroupReports { get; set; }
    }
}
