//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string FormatReport { get; set; }
        public bool IsEnabled { get; set; }
        public int GroupID { get; set; }
    
        public virtual GroupReports GroupReports { get; set; }
    }
}
