//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saAjPrecioCostoM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saAjPrecioCostoM()
        {
            this.saAjPrecioCostoReng = new HashSet<saAjPrecioCostoReng>();
        }
    
        public string cod_ajuste { get; set; }
        public string des_ajuste { get; set; }
        public string co_alma { get; set; }
        public int tipo_ajuste { get; set; }
        public string tipo_ajuste_precio { get; set; }
        public string tipo_ajuste_costo { get; set; }
        public string margen_superior { get; set; }
        public string margen_inferior { get; set; }
        public string co_art_desde { get; set; }
        public string co_art_hasta { get; set; }
        public string co_lin { get; set; }
        public string co_subl { get; set; }
        public string co_cat { get; set; }
        public string co_prov { get; set; }
        public string item { get; set; }
        public bool procesado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public string co_mone { get; set; }
        public Nullable<decimal> tasa { get; set; }
    
        public virtual saMoneda saMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saAjPrecioCostoReng> saAjPrecioCostoReng { get; set; }
    }
}
