//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saAjPrecioCostoAuto
    {
        public string cod_ajuste { get; set; }
        public string des_ajuste { get; set; }
        public string co_alma { get; set; }
        public int tipo_ajuste { get; set; }
        public string tipo_ajuste_precio { get; set; }
        public string tipo_ajuste_costo { get; set; }
        public Nullable<int> metodo { get; set; }
        public Nullable<int> tipo_calculo { get; set; }
        public decimal valor { get; set; }
        public decimal factor { get; set; }
        public bool redondeo { get; set; }
        public Nullable<int> tipo_redondeo { get; set; }
        public string valor_redondeo { get; set; }
        public string margen_superior { get; set; }
        public string margen_inferior { get; set; }
        public string condicion1 { get; set; }
        public string condicion2 { get; set; }
        public Nullable<decimal> valor_condicion1 { get; set; }
        public Nullable<int> operador_logico { get; set; }
        public Nullable<decimal> valor_condicion2 { get; set; }
        public string co_art_desde { get; set; }
        public string co_art_hasta { get; set; }
        public string co_lin_desde { get; set; }
        public string co_lin_hasta { get; set; }
        public string co_subl_desde { get; set; }
        public string co_subl_hasta { get; set; }
        public string co_cat_desde { get; set; }
        public string co_cat_hasta { get; set; }
        public string co_prov_desde { get; set; }
        public string co_prov_hasta { get; set; }
        public string item_desde { get; set; }
        public string item_hasta { get; set; }
        public Nullable<System.DateTime> vigencia_desde { get; set; }
        public Nullable<System.DateTime> vigencia_hasta { get; set; }
        public bool basado_en { get; set; }
        public string basado_en_costo { get; set; }
        public Nullable<System.DateTime> basado_en_fecha { get; set; }
        public string basado_en_co_alma { get; set; }
        public bool procesado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public string co_mone { get; set; }
        public Nullable<decimal> tasa { get; set; }
    
        public virtual saAlmacen saAlmacen { get; set; }
        public virtual saMoneda saMoneda { get; set; }
    }
}
