//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saArtUbicacion
    {
        public string co_art { get; set; }
        public string co_alma { get; set; }
        public string co_ubicacion { get; set; }
        public string co_ubicacion2_calculado { get; set; }
        public string co_ubicacion3_calculado { get; set; }
        public int orden { get; set; }
        public string co_ubicacion2 { get; set; }
        public string co_ubicacion3 { get; set; }
        public string des_ubicacion { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual saAlmacen saAlmacen { get; set; }
        public virtual saArticulo saArticulo { get; set; }
        public virtual saUbicacion saUbicacion { get; set; }
        public virtual saUbicacion saUbicacion1 { get; set; }
        public virtual saUbicacion saUbicacion2 { get; set; }
    }
}
