//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saArtCaracteristicaMov
    {
        public System.Guid rowguidDoc { get; set; }
        public string tipo_doc { get; set; }
        public string co_lin01 { get; set; }
        public string co_subl01 { get; set; }
        public string co_lin02 { get; set; }
        public string co_subl02 { get; set; }
        public string co_lin03 { get; set; }
        public string co_subl03 { get; set; }
        public string co_lin04 { get; set; }
        public string co_subl04 { get; set; }
        public string co_lin05 { get; set; }
        public string co_subl05 { get; set; }
        public decimal cantidad { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saSubLinea saSubLinea { get; set; }
        public virtual saSubLinea saSubLinea1 { get; set; }
        public virtual saSubLinea saSubLinea2 { get; set; }
        public virtual saSubLinea saSubLinea3 { get; set; }
        public virtual saSubLinea saSubLinea4 { get; set; }
    }
}
