//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saCheque
    {
        public string co_cheq { get; set; }
        public string co_chra { get; set; }
        public string mov_num { get; set; }
        public string Status { get; set; }
        public string descrip { get; set; }
        public Nullable<System.DateTime> fec_emis { get; set; }
        public Nullable<System.DateTime> fec_ent { get; set; }
        public string entreg_a { get; set; }
        public string comentario { get; set; }
        public string co_us_In { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
        public byte[] validador { get; set; }
    
        public virtual saChequera saChequera { get; set; }
        public virtual saMovimientoBanco saMovimientoBanco { get; set; }
    }
}
