//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saChequeDevueltoVenta
    {
        public string co_cheq_dev { get; set; }
        public string des_cheq_dev { get; set; }
        public string co_cli { get; set; }
        public System.DateTime fecha { get; set; }
        public string num_doc { get; set; }
        public bool incluye_imp { get; set; }
        public string cod_caja { get; set; }
        public string co_tipo_doc { get; set; }
        public string co_ven { get; set; }
        public string nro_doc { get; set; }
        public decimal mont_doc { get; set; }
        public System.DateTime fec_cheq { get; set; }
        public string co_ban { get; set; }
        public string tip_imp { get; set; }
        public bool procesado { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public byte[] validador { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
        public bool automatico { get; set; }
        public string cod_cta { get; set; }
    
        public virtual saDocumentoVenta saDocumentoVenta { get; set; }
        public virtual saCliente saCliente { get; set; }
    }
}
