//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saCliente()
        {
            this.saChequeDevueltoVenta = new HashSet<saChequeDevueltoVenta>();
            this.saCliente1 = new HashSet<saCliente>();
            this.saCobro = new HashSet<saCobro>();
            this.saCotizacionCliente = new HashSet<saCotizacionCliente>();
            this.saDevolucionCliente = new HashSet<saDevolucionCliente>();
            this.saDocumentoElectronico = new HashSet<saDocumentoElectronico>();
            this.saDocumentoElectronico1 = new HashSet<saDocumentoElectronico>();
            this.saDocumentoVenta = new HashSet<saDocumentoVenta>();
            this.saFacturaVenta = new HashSet<saFacturaVenta>();
            this.saNotaDespachoVenta = new HashSet<saNotaDespachoVenta>();
            this.saNotaEntregaVenta = new HashSet<saNotaEntregaVenta>();
            this.saPedidoVenta = new HashSet<saPedidoVenta>();
            this.saPlantillaVenta = new HashSet<saPlantillaVenta>();
            this.stgFactLoteGen = new HashSet<stgFactLoteGen>();
            this.stgFactLoteGen1 = new HashSet<stgFactLoteGen>();
        }
    
        public string co_cli { get; set; }
        public string tip_cli { get; set; }
        public string cli_des { get; set; }
        public string direc1 { get; set; }
        public string dir_ent2 { get; set; }
        public string direc2 { get; set; }
        public string telefonos { get; set; }
        public string fax { get; set; }
        public bool inactivo { get; set; }
        public string comentario { get; set; }
        public string respons { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public int puntaje { get; set; }
        public decimal mont_cre { get; set; }
        public string co_mone { get; set; }
        public string cond_pag { get; set; }
        public int plaz_pag { get; set; }
        public decimal desc_ppago { get; set; }
        public string co_zon { get; set; }
        public string co_seg { get; set; }
        public string co_ven { get; set; }
        public decimal desc_glob { get; set; }
        public string horar_caja { get; set; }
        public string frecu_vist { get; set; }
        public bool lunes { get; set; }
        public bool martes { get; set; }
        public bool miercoles { get; set; }
        public bool jueves { get; set; }
        public bool viernes { get; set; }
        public bool sabado { get; set; }
        public bool domingo { get; set; }
        public string rif { get; set; }
        public string nit { get; set; }
        public bool contrib { get; set; }
        public Nullable<int> numcom { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public string dis_cen { get; set; }
        public string email { get; set; }
        public string co_cta_ingr_egr { get; set; }
        public bool juridico { get; set; }
        public int tipo_adi { get; set; }
        public string matriz { get; set; }
        public string co_tab { get; set; }
        public string tipo_per { get; set; }
        public bool valido { get; set; }
        public string ciudad { get; set; }
        public string zip { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string website { get; set; }
        public bool sincredito { get; set; }
        public bool contribu_e { get; set; }
        public bool rete_regis_doc { get; set; }
        public decimal porc_esp { get; set; }
        public string co_pais { get; set; }
        public string serialp { get; set; }
        public int Id { get; set; }
        public string salestax { get; set; }
        public string estado { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public string email_alterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saChequeDevueltoVenta> saChequeDevueltoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saCliente> saCliente1 { get; set; }
        public virtual saCliente saCliente2 { get; set; }
        public virtual saCondicionPago saCondicionPago { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr { get; set; }
        public virtual saMoneda saMoneda { get; set; }
        public virtual saPais saPais { get; set; }
        public virtual saSegmento saSegmento { get; set; }
        public virtual saTabuladorIslr saTabuladorIslr { get; set; }
        public virtual saTipoCliente saTipoCliente { get; set; }
        public virtual saVendedor saVendedor { get; set; }
        public virtual saZona saZona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saCobro> saCobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saCotizacionCliente> saCotizacionCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDevolucionCliente> saDevolucionCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoElectronico> saDocumentoElectronico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoElectronico> saDocumentoElectronico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoVenta> saDocumentoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saFacturaVenta> saFacturaVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saNotaDespachoVenta> saNotaDespachoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saNotaEntregaVenta> saNotaEntregaVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saPedidoVenta> saPedidoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saPlantillaVenta> saPlantillaVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stgFactLoteGen> stgFactLoteGen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stgFactLoteGen> stgFactLoteGen1 { get; set; }
    }
}
