//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saConsecutivo
    {
        public string co_emp { get; set; }
        public string co_sucur { get; set; }
        public string codigo { get; set; }
        public string co_consecutivo { get; set; }
        public string co_serie { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public byte[] validador { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
        public string co_sucu_in { get; set; }
        public string co_sucu_mo { get; set; }
    
        public virtual par_emp par_emp { get; set; }
        public virtual saConsecutivoTipo saConsecutivoTipo { get; set; }
        public virtual saSucursal saSucursal { get; set; }
    }
}
