//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saConciliacionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saConciliacionDetalle()
        {
            this.saConcBanco = new HashSet<saConcBanco>();
        }
    
        public string co_auto_con { get; set; }
        public int reng_num { get; set; }
        public System.DateTime fec_mov { get; set; }
        public string doc_num { get; set; }
        public string tipo_op { get; set; }
        public string descrip { get; set; }
        public decimal monto_d { get; set; }
        public decimal monto_h { get; set; }
        public decimal idb { get; set; }
        public string origen { get; set; }
        public bool dep_con { get; set; }
        public bool repetido { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saConcBanco> saConcBanco { get; set; }
        public virtual saConciliacionAutoReng saConciliacionAutoReng { get; set; }
    }
}
