//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saDepositoBancoReng
    {
        public string dep_num { get; set; }
        public int reng_num { get; set; }
        public string codigo { get; set; }
        public string mov_afec_c { get; set; }
        public string mov_gene_c { get; set; }
        public decimal monto { get; set; }
        public decimal comision { get; set; }
        public decimal porc_comision { get; set; }
        public decimal porc_impuesto { get; set; }
        public decimal impuesto { get; set; }
        public string tipo_plazo { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public Nullable<int> numcom { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saCaja saCaja { get; set; }
        public virtual saDepositoBanco saDepositoBanco { get; set; }
        public virtual saMovimientoCaja saMovimientoCaja { get; set; }
        public virtual saMovimientoCaja saMovimientoCaja1 { get; set; }
    }
}
