//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saDepositoBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saDepositoBanco()
        {
            this.saDepositoBancoReng = new HashSet<saDepositoBancoReng>();
        }
    
        public string dep_num { get; set; }
        public string deposito { get; set; }
        public System.DateTime fecha { get; set; }
        public string cod_cta { get; set; }
        public string cod_caja { get; set; }
        public string mov_num_b { get; set; }
        public string mov_num_c { get; set; }
        public decimal total_efec { get; set; }
        public int che_dev { get; set; }
        public string co_cta_ingr_egr { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public Nullable<int> numcom { get; set; }
        public string dis_cen { get; set; }
        public decimal tasa { get; set; }
        public Nullable<decimal> aux01 { get; set; }
        public string aux02 { get; set; }
        public bool activado { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saCaja saCaja { get; set; }
        public virtual saCuentaBancaria saCuentaBancaria { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDepositoBancoReng> saDepositoBancoReng { get; set; }
    }
}
