//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saDocumentoElectronico
    {
        public string co_doc_elec { get; set; }
        public string des_doc_elec { get; set; }
        public System.DateTime fec_doc_elec { get; set; }
        public string co_grupo_rep { get; set; }
        public string co_reporte { get; set; }
        public string sp_doc_elec { get; set; }
        public string doc_num_desde { get; set; }
        public string doc_num_hasta { get; set; }
        public Nullable<System.DateTime> fec_emis_desde { get; set; }
        public Nullable<System.DateTime> fec_emis_hasta { get; set; }
        public Nullable<System.DateTime> fec_venc_desde { get; set; }
        public Nullable<System.DateTime> fec_venc_hasta { get; set; }
        public string co_cli_desde { get; set; }
        public string co_cli_hasta { get; set; }
        public string co_prov_desde { get; set; }
        public string co_prov_hasta { get; set; }
        public string status { get; set; }
        public Nullable<int> tipo_doc_salida { get; set; }
        public bool enviarcorreo { get; set; }
        public bool mantenerarchivos { get; set; }
        public string ruta_arch { get; set; }
        public string correo_asunto { get; set; }
        public string correo_cc { get; set; }
        public string correo_bcc { get; set; }
        public string correo_cuerpo { get; set; }
        public string correo_firma { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
        public bool procesado { get; set; }
        public string Log { get; set; }
        public string tipo_documento { get; set; }
    
        public virtual saCliente saCliente { get; set; }
        public virtual saCliente saCliente1 { get; set; }
        public virtual saProveedor saProveedor { get; set; }
        public virtual saProveedor saProveedor1 { get; set; }
    }
}
