//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saDocumentoCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saDocumentoCompra()
        {
            this.saChequeDevueltoCompra = new HashSet<saChequeDevueltoCompra>();
            this.saDevolucionProveedor = new HashSet<saDevolucionProveedor>();
            this.saDocumentoCompraReng = new HashSet<saDocumentoCompraReng>();
            this.saGiroCompraReng = new HashSet<saGiroCompraReng>();
            this.saPagoDocReng = new HashSet<saPagoDocReng>();
        }
    
        public string co_tipo_doc { get; set; }
        public string nro_doc { get; set; }
        public string nro_fact { get; set; }
        public string co_mone { get; set; }
        public string co_prov { get; set; }
        public string doc_orig { get; set; }
        public string mov_ban { get; set; }
        public string nro_orig { get; set; }
        public string nro_che { get; set; }
        public string porc_reca { get; set; }
        public decimal monto_reca { get; set; }
        public string porc_desc_glob { get; set; }
        public decimal monto_desc_glob { get; set; }
        public bool anulado { get; set; }
        public bool aut { get; set; }
        public int pagar { get; set; }
        public string observa { get; set; }
        public string tipo_imp { get; set; }
        public string tipo_imp2 { get; set; }
        public string tipo_imp3 { get; set; }
        public System.DateTime fec_reg { get; set; }
        public System.DateTime fec_emis { get; set; }
        public System.DateTime fec_venc { get; set; }
        public decimal porc_imp { get; set; }
        public decimal porc_imp2 { get; set; }
        public decimal porc_imp3 { get; set; }
        public decimal monto_imp { get; set; }
        public decimal monto_imp2 { get; set; }
        public decimal monto_imp3 { get; set; }
        public decimal tasa { get; set; }
        public decimal total_bruto { get; set; }
        public decimal total_neto { get; set; }
        public decimal saldo { get; set; }
        public decimal adicional { get; set; }
        public decimal otros1 { get; set; }
        public decimal otros2 { get; set; }
        public decimal otros3 { get; set; }
        public string pro_pago { get; set; }
        public string salestax { get; set; }
        public string prov_ter { get; set; }
        public Nullable<int> reng_ter { get; set; }
        public Nullable<int> tipo_origen { get; set; }
        public string num_comprobante { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public Nullable<int> numcom { get; set; }
        public string dis_cen { get; set; }
        public string n_control { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
        public byte[] validador { get; set; }
        public Nullable<bool> nac { get; set; }
        public string co_cta_ingr_egr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saChequeDevueltoCompra> saChequeDevueltoCompra { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDevolucionProveedor> saDevolucionProveedor { get; set; }
        public virtual saMoneda saMoneda { get; set; }
        public virtual saMovimientoBanco saMovimientoBanco { get; set; }
        public virtual saProveedor saProveedor { get; set; }
        public virtual saProveedor saProveedor1 { get; set; }
        public virtual saTipoDocumento saTipoDocumento { get; set; }
        public virtual saTipoDocumento saTipoDocumento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoCompraReng> saDocumentoCompraReng { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saGiroCompraReng> saGiroCompraReng { get; set; }
        public virtual saNCFInfoDocCompra saNCFInfoDocCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saPagoDocReng> saPagoDocReng { get; set; }
    }
}
