//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saFactCompRengCaracteristicasAdic
    {
        public System.Guid doc_orig { get; set; }
        public decimal volumen_neto { get; set; }
        public decimal peso_neto { get; set; }
    
        public virtual saFactCompRengCaracteristicasAdic saFactCompRengCaracteristicasAdic1 { get; set; }
        public virtual saFactCompRengCaracteristicasAdic saFactCompRengCaracteristicasAdic2 { get; set; }
    }
}
