//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saHistoricoEstado
    {
        public System.Guid rowguid { get; set; }
        public System.Guid doc_orig { get; set; }
        public string tipo_doc { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
        public byte[] validador { get; set; }
    }
}
