//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saInventarioFisico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saInventarioFisico()
        {
            this.saAjuste = new HashSet<saAjuste>();
            this.saResInventario = new HashSet<saResInventario>();
        }
    
        public string co_invfisico { get; set; }
        public string des_invfisico { get; set; }
        public string co_alma { get; set; }
        public System.DateTime inicio { get; set; }
        public Nullable<System.DateTime> cierre { get; set; }
        public bool art_cero { get; set; }
        public string ajue_num { get; set; }
        public string co_tipo_ent { get; set; }
        public string co_tipo_sal { get; set; }
        public bool procesado { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saAjuste> saAjuste { get; set; }
        public virtual saAlmacen saAlmacen { get; set; }
        public virtual saTipoAjuste saTipoAjuste { get; set; }
        public virtual saTipoAjuste saTipoAjuste1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saResInventario> saResInventario { get; set; }
    }
}
