//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saPagoRentenReng
    {
        public int reng_num { get; set; }
        public System.Guid rowguid_reng_cob { get; set; }
        public string co_islr { get; set; }
        public decimal monto { get; set; }
        public decimal monto_reten { get; set; }
        public decimal monto_obj { get; set; }
        public decimal sustraendo { get; set; }
        public decimal porc_retn { get; set; }
        public bool automatica { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<System.Guid> rowguid_fact { get; set; }
    
        public virtual saConISLR saConISLR { get; set; }
    }
}
