//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saPista
    {
        public System.DateTime fecha { get; set; }
        public string tablaOri { get; set; }
        public Nullable<System.Guid> rowguidOri { get; set; }
        public string usuario_id { get; set; }
        public string co_sucu { get; set; }
        public string tipo_op { get; set; }
        public string maquina { get; set; }
        public string campos { get; set; }
        public Nullable<decimal> aux01 { get; set; }
        public string aux02 { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
