//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saPlantillaCompraReq
    {
        public System.Guid rowguid_plantilla_compra { get; set; }
        public string co_ubicacion { get; set; }
        public string autorizado { get; set; }
        public string descripcion { get; set; }
        public string responsable { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estatus { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saUbicacion saUbicacion { get; set; }
    }
}
