//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saSerie
    {
        public int reng_num { get; set; }
        public string co_tipo_serie { get; set; }
        public string co_serie { get; set; }
        public string desde_a { get; set; }
        public Nullable<long> desde_n { get; set; }
        public string hasta_a { get; set; }
        public Nullable<long> hasta_n { get; set; }
        public string prox_a { get; set; }
        public Nullable<long> prox_n { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saSerieTipo saSerieTipo { get; set; }
    }
}
