//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saSeriales
    {
        public System.Guid rowguid { get; set; }
        public int reng_num { get; set; }
        public string co_art { get; set; }
        public string co_alma { get; set; }
        public string serial { get; set; }
        public string doc_tip_e { get; set; }
        public Nullable<System.Guid> doc_num_e { get; set; }
        public string doc_tip_s { get; set; }
        public Nullable<System.Guid> doc_num_s { get; set; }
        public Nullable<int> num_gara { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
    
        public virtual saAlmacen saAlmacen { get; set; }
        public virtual saArticulo saArticulo { get; set; }
    }
}
