//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saTipoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saTipoDocumento()
        {
            this.saDocumentoCompra = new HashSet<saDocumentoCompra>();
            this.saDocumentoCompra1 = new HashSet<saDocumentoCompra>();
            this.saDocumentoVenta = new HashSet<saDocumentoVenta>();
            this.saDocumentoVenta1 = new HashSet<saDocumentoVenta>();
        }
    
        public string co_tipo_doc { get; set; }
        public string descrip { get; set; }
        public string tipo_mov { get; set; }
        public bool usar_ventas { get; set; }
        public bool usar_compras { get; set; }
        public bool registro_sistema { get; set; }
        public bool num_fact_fis_venta { get; set; }
        public bool num_cont_venta { get; set; }
        public bool serial_imp_fis_venta { get; set; }
        public bool reng_venta { get; set; }
        public bool num_iva_venta { get; set; }
        public bool reac_doc_Compra { get; set; }
        public bool reac_doc_Venta { get; set; }
        public bool anul_doc_venta { get; set; }
        public bool anul_doc_compra { get; set; }
        public bool doc_prov_compra { get; set; }
        public bool num_control_compra { get; set; }
        public bool reng_compra { get; set; }
        public bool num_iva_compra { get; set; }
        public bool manual_venta { get; set; }
        public bool manual_compra { get; set; }
        public bool doc_asoc_compra { get; set; }
        public bool doc_asoc_venta { get; set; }
        public bool act_prog_pago { get; set; }
        public bool aplica_dxpp_venta { get; set; }
        public bool aplica_dxpp_compra { get; set; }
        public bool aplica_riva_venta { get; set; }
        public bool aplica_riva_compra { get; set; }
        public string tipo_imp { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public byte[] validador { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoCompra> saDocumentoCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoCompra> saDocumentoCompra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoVenta> saDocumentoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoVenta> saDocumentoVenta1 { get; set; }
    }
}
