//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saTraslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saTraslado()
        {
            this.saTrasladoReng = new HashSet<saTrasladoReng>();
        }
    
        public string tras_num { get; set; }
        public string motivo_glo { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal tasa { get; set; }
        public string co_mone { get; set; }
        public string alm_orig { get; set; }
        public string alm_tmp { get; set; }
        public string alm_dest { get; set; }
        public Nullable<decimal> monto_dist { get; set; }
        public bool confirma { get; set; }
        public System.DateTime fec_sal { get; set; }
        public Nullable<System.DateTime> fec_conf { get; set; }
        public bool anulado { get; set; }
        public Nullable<int> seriales_s { get; set; }
        public Nullable<int> seriales_e { get; set; }
        public Nullable<int> numcom { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public string dis_cen { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saAlmacen saAlmacen { get; set; }
        public virtual saAlmacen saAlmacen1 { get; set; }
        public virtual saAlmacen saAlmacen2 { get; set; }
        public virtual saMoneda saMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saTrasladoReng> saTrasladoReng { get; set; }
    }
}
