//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saTransferenciaEntreCuentas
    {
        public string co_trans_ban { get; set; }
        public string des_trans_ban { get; set; }
        public System.DateTime fecha { get; set; }
        public bool procesado { get; set; }
        public decimal monto { get; set; }
        public Nullable<decimal> comision { get; set; }
        public string cta_origen { get; set; }
        public string cta_ingr_egr_origen { get; set; }
        public System.DateTime fecha_origen { get; set; }
        public string mov_ban_origen { get; set; }
        public string referencia_origen { get; set; }
        public string cta_comision { get; set; }
        public string cta_ingr_egr_comision { get; set; }
        public string mov_ban_comision { get; set; }
        public string cta_destino { get; set; }
        public string cta_ingr_egr_destino { get; set; }
        public System.DateTime fecha_destino { get; set; }
        public string mov_ban_destino { get; set; }
        public string referencia_destino { get; set; }
        public decimal tasa_origen { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public decimal tasa { get; set; }
        public string referencia_comis { get; set; }
    
        public virtual saCuentaBancaria saCuentaBancaria { get; set; }
        public virtual saCuentaBancaria saCuentaBancaria1 { get; set; }
        public virtual saCuentaBancaria saCuentaBancaria2 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr1 { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr2 { get; set; }
        public virtual saMovimientoBanco saMovimientoBanco { get; set; }
        public virtual saMovimientoBanco saMovimientoBanco1 { get; set; }
        public virtual saMovimientoBanco saMovimientoBanco2 { get; set; }
    }
}
