//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scCuenta
    {
        public string co_cue { get; set; }
        public string des_cue { get; set; }
        public bool detalle { get; set; }
        public bool aj_islr { get; set; }
        public int me_islr { get; set; }
        public bool aj_dpc { get; set; }
        public int me_dpc { get; set; }
        public int opciones { get; set; }
        public Nullable<decimal> saldo_ini { get; set; }
        public decimal saldan { get; set; }
        public string centro_co { get; set; }
        public bool moneda_adi { get; set; }
        public bool man_aux { get; set; }
        public string tipoaux { get; set; }
        public bool man_doc { get; set; }
        public bool man_fecdoc { get; set; }
        public bool cue_gasto { get; set; }
        public string co_gas { get; set; }
        public bool man_adi { get; set; }
        public string co_tab { get; set; }
        public bool man_adi2 { get; set; }
        public string co_tab2 { get; set; }
        public bool man_adi3 { get; set; }
        public string co_tab3 { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public bool inactivo { get; set; }
        public Nullable<System.DateTime> fec_inac { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public string co_cuepadre { get; set; }
        public int tipo_pat { get; set; }
        public bool flujo_efe { get; set; }
        public bool afecta_pm { get; set; }
        public int tipo_inv { get; set; }
        public int ipc_islr { get; set; }
        public int ipc_dpc { get; set; }
        public bool exc_pat { get; set; }
        public int meses_rotacion { get; set; }
        public byte[] validador { get; set; }
    }
}
