//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stgFactLoteGen
    {
        public string co_fact_lote_gen { get; set; }
        public string descrip { get; set; }
        public System.DateTime fecha { get; set; }
        public bool procesado { get; set; }
        public string co_cli_d { get; set; }
        public string co_cli_h { get; set; }
        public string co_serie_fact { get; set; }
        public string co_serie_nctrl { get; set; }
        public bool man_ven_pl { get; set; }
        public bool man_cond_pl { get; set; }
        public System.DateTime fec_emis { get; set; }
        public System.DateTime fec_venc { get; set; }
        public System.DateTime fec_reg { get; set; }
        public bool man_fec_emis { get; set; }
        public bool man_fec_venc { get; set; }
        public bool man_fec_reg { get; set; }
        public bool prec_vta_act { get; set; }
        public string co_usuario { get; set; }
        public string co_sucu { get; set; }
        public string co_plan_vta { get; set; }
        public string sp_usuario { get; set; }
        public string arch_cod { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual saCliente saCliente { get; set; }
        public virtual saCliente saCliente1 { get; set; }
        public virtual saPlantillaVenta saPlantillaVenta { get; set; }
    }
}
