//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfers
    {
        public int ID { get; set; }
        public string AccountID { get; set; }
        public string UserID { get; set; }
        public string DocNum { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public bool Concilied { get; set; }
        public int BoxID { get; set; }
        public bool Cancelled { get; set; }
        public System.DateTime DateReg { get; set; }
        public string ConciliedBy { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> DateConcilied { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
    
        public virtual Boxes Boxes { get; set; }
    }
}
