//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfers
    {
        public int ID { get; set; }
        public string AccountID { get; set; }
        public string UserID { get; set; }
        public string DocNum { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public bool Concilied { get; set; }
        public int BoxID { get; set; }
        public bool Cancelled { get; set; }
        public System.DateTime DateReg { get; set; }
        public string ConciliedBy { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> DateConcilied { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
    
        public virtual Boxes Boxes { get; set; }
    }
}
