//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.UserModules = new HashSet<UserModules>();
            this.UserOptions = new HashSet<UserOptions>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Descrip { get; set; }
        public System.DateTime DateReg { get; set; }
        public string CI { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsAdm { get; set; }
        public bool IsCon { get; set; }
        public bool IsNom { get; set; }
        public bool Enabled { get; set; }
        public bool Admin { get; set; }
        public System.DateTime NextChange { get; set; }
        public bool UseBox { get; set; }
        public Nullable<int> SupID { get; set; }
        public Nullable<int> BoxType { get; set; }
        public bool AllowCollect { get; set; }
        public bool AllowCancel { get; set; }
        public bool UseAlterSerie { get; set; }
        public bool AllowCredit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserModules> UserModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOptions> UserOptions { get; set; }
    }
}
