//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOptions
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int OptionID { get; set; }
    
        public virtual Options Options { get; set; }
        public virtual Users Users { get; set; }
    }
}
